import { guideArtwork } from "./artwork";
import type { CornerstoneGuide } from "./cornerstones";

const sources = {
  market: { label: "SBA: Plan your business — market research and startup costs", href: "https://www.sba.gov/counseling/plan-your-business/" },
  sensory: { label: "Cornell: Sensory Evaluation Center", href: "https://cals.cornell.edu/food-science/outreach-extension/sensory-evaluation-center" },
  fda: { label: "FDA: How to Start a Food Business", href: "https://www.fda.gov/food/food-industry/how-start-food-business" },
  labels: { label: "FDA: Nutrition, Food Labeling, and Critical Foods", href: "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods" },
  development: { label: "Cornell: Seneca Foods Foundation Pilot Plant", href: "https://cals.cornell.edu/cornell-agritech/partners-institutes/cornell-food-venture-center/seneca-foods-foundation-pilot-plant" },
  expert: { label: "Cornell Food Venture Center: Frequently Asked Questions", href: "https://cals.cornell.edu/cornell-agritech/partners-institutes/cornell-food-venture-center/frequently-asked-questions" },
  uf: { label: "UF/IFAS Extension: Finding and Using a Co-packer", href: "https://ask.ifas.ufl.edu/publication/FS380" },
  ncsu: { label: "NC State Extension: Choosing and Using a Copacker", href: "https://content.ces.ncsu.edu/choosing-and-using-a-copacker" },
};

const dates = { reviewedLabel: "10 Sep 2026", datePublished: "2026-09-10", dateModified: "2026-09-10" };

export const FOUNDER_GUIDES: CornerstoneGuide[] = [
  {
    slug: "test-food-business-idea",
    title: "How to test your food or drink business idea",
    seoTitle: "How to Test a Food Business Idea Before Manufacturing",
    description: "Work out who might buy your product, what they use today, and what you need to learn before committing to a production run.",
    eyebrow: "Start with an idea",
    image: guideArtwork("test-food-business-idea").src,
    imageAlt: guideArtwork("test-food-business-idea").alt,
    directAnswer: "Start with one likely customer and one buying occasion. Talk about what they already buy, compare the alternatives, and test the question you are least sure about. Record what you learn before choosing a large first run. Interest in an idea does not establish demand, product safety, or manufacturing readiness.",
    whoThisIsFor: "You have a packaged food or beverage idea and want a useful first step. You do not need a logo, a finished recipe, or a manufacturer to begin learning about customers.",
    ...dates,
    diagram: "idea-test",
    steps: [
      { title: "Describe one customer and occasion", text: "Try: a person who wants a savory snack on their afternoon commute. Write what they buy now and what you want to make easier, tastier, or more convenient. Keep this as a hypothesis until you hear from customers." },
      { title: "Look at the real alternatives", text: "Visit the place you hope to sell. Record package size, price, storage, claims, and where similar products sit. Compare the same unit size. Include the option of buying something completely different." },
      { title: "Ask about recent behavior", text: "Ask someone to describe the last time they bought a product for that occasion. What did they choose, where, and why? Avoid leading with a sales pitch. Record objections as carefully as compliments." },
      { title: "Choose one small learning exercise", text: "You might compare two plain concept descriptions, discuss a package mockup, or ask a prospective shop buyer about ordering needs. If you plan tasting, sampling, or sales, first confirm the relevant food-safety, allergen, and local requirements. A concept conversation needs no edible sample." },
      { title: "Decide what changes next", text: "Write down the question, what you observed, what remains uncertain, and the change you will make. Keep research notes private. Save a tentative first selling channel in your product plan and revisit it when you have better evidence." },
    ],
    checklist: ["I can describe one likely customer and buying occasion.", "I have compared the alternatives in my intended selling channel.", "I have written down actual customer questions or observations.", "I have chosen one question to test next.", "I know which professional or local guidance I need before sampling or selling."],
    decisions: [
      { decision: "Who is it for?", why: "A specific buying occasion gives you something concrete to investigate." },
      { decision: "Where might it sell first?", why: "Direct sales and retail buyers raise different questions about price, package, and ordering." },
      { decision: "What evidence would change your mind?", why: "Deciding this before an exercise helps you notice inconvenient feedback." },
    ],
    definitions: [{ term: "Customer hypothesis", meaning: "A statement about a buyer that you still need to investigate." }, { term: "Selling channel", meaning: "How your product reaches a buyer, such as your website or a local shop." }, { term: "Concept test", meaning: "Feedback on a product idea before committing to its final recipe or package." }],
    questions: ["Do you work with founders who still need product development?", "What information would you need before discussing a trial?", "Which product and packaging choices would change the first-run commitment?"],
    mistakes: ["Treating likes or compliments as confirmed orders.", "Only asking friends who want to encourage you.", "Using a small informal conversation as a sales forecast.", "Assuming a kitchen recipe can be sampled or sold under the same rules everywhere."],
    faq: [{ question: "Do I need a finished product to test an idea?", answer: "You can learn about buying habits and reactions to a concept before a finished recipe exists. Tasting and sales add product-safety and local requirements; verify those before offering food." }, { question: "How many conversations prove demand?", answer: "There is no universal number. Early conversations help uncover questions and improve an idea; they do not by themselves establish market size or predict sales." }],
    directoryHref: "/find-manufacturers", directoryLabel: "Explore manufacturers when you know the help you need",
    relatedLinks: [{ href: "/guides/food-product-development", label: "Find the right recipe-development help" }, { href: "/guides/first-run-costs", label: "Explore first-run costs" }, { href: "/guides/start-hot-sauce", label: "Work through a hot sauce idea" }],
    sources: [sources.market, sources.sensory, sources.fda],
  },
  {
    slug: "food-product-development",
    title: "Who can help turn your recipe into a food product?",
    seoTitle: "Food Product Development: Recipe, Packaging, and Label Help",
    description: "Understand the roles of a food scientist, process authority, packaging specialist, label reviewer, shared kitchen, and manufacturer.",
    eyebrow: "From recipe to product",
    image: guideArtwork("food-product-development").src,
    imageAlt: guideArtwork("food-product-development").alt,
    directAnswer: "Start by naming the help you need. Recipe development, product-safety review, package fit, label review, and manufacturing are different jobs. One provider may cover several, but ask about the exact scope and deliverables. A finished home recipe can still need commercial development and testing.",
    whoThisIsFor: "You have a food or drink idea or home recipe and are unsure who to approach before a manufacturer can evaluate it.",
    ...dates,
    diagram: "development-help",
    steps: [
      { title: "Write what exists today", text: "State whether you have only an idea, a home recipe, a measured formula, or prior production experience. List the decisions that are fixed and those you can change. Do not upgrade the description to production-ready just to sound prepared." },
      { title: "Ask for the missing expertise", text: "A product developer or food scientist may help refine the formula and plan trials. A qualified process authority addresses applicable process and stability questions. Ask a university food-science or extension program which services fit your product and location." },
      { title: "Review the real package and label", text: "Discuss container and closure compatibility with your manufacturer and packaging supplier. Identify who will review ingredients, allergens, nutrition information, and intended claims before printing labels. Attractive artwork does not establish compliance." },
      { title: "Choose the right place to develop", text: "A shared kitchen offers space and equipment for your own work; confirm its services and permitted uses. A pilot facility can help investigate scale-up questions. A co-manufacturer produces for other brands. Ask who performs each task before assuming the facility provides it." },
      { title: "Agree on what you will receive", text: "Request a written scope describing trials, samples, specifications, test results, costs, and ownership of the work. Ask what you can take to another manufacturer. Save your recipe stage in your product plan with unresolved needs clearly stated." },
    ],
    checklist: ["I have described my current recipe stage honestly.", "I have listed the development or testing help I need.", "I know who will review the process and storage claims.", "I know who will check package compatibility and label content.", "I have questions about deliverables, costs, and ownership before hiring help."],
    decisions: [{ decision: "Recipe development or production?", why: "The person refining a recipe may not be the facility making the finished product." }, { decision: "Make it yourself or hire production?", why: "Kitchen rental and outsourced manufacturing require different time, skills, and responsibilities." }, { decision: "Who checks each claim?", why: "Safety, shelf life, packaging, and labels need the relevant expertise and product-specific evidence." }],
    definitions: [{ term: "Food scientist / product developer", meaning: "A specialist who can help turn product goals into a workable formula and development plan; services vary." }, { term: "Process authority", meaning: "A qualified expert who evaluates applicable food-process safety and stability requirements." }, { term: "Pilot trial", meaning: "A controlled development run used to investigate production questions before committing to a full run." }],
    questions: ["Which development tasks do you perform and which need another specialist?", "What recipe and package information should I bring to a trial?", "Who owns the formula and test results, and which deliverables can I take elsewhere?", "Who reviews label content and any storage or shelf-life statement?"],
    mistakes: ["Assuming every manufacturer offers recipe development.", "Ordering printed packaging before confirming the actual line and label requirements.", "Treating a package mockup as proof of production compatibility.", "Expecting a shared kitchen to manufacture the product for you without checking its services."],
    faq: [{ question: "Can I approach a manufacturer without a finished recipe?", answer: "Yes, for an initial fit conversation. Clearly state your recipe stage and ask whether development help is available. The manufacturer may require further work before a quote or trial." }, { question: "Where can I find qualified help?", answer: "Start with university food-science and extension programs, the relevant local food-business authority, and specialists with experience in your product category. Confirm each provider’s scope, availability, and fees directly." }],
    directoryHref: "/find-manufacturers?help=production", directoryLabel: "Explore outsourced manufacturing",
    relatedLinks: [{ href: "/guides/packaging-formats", label: "Choose a packaging direction" }, { href: "/guides/manufacturer-inquiry-examples", label: "See a useful first inquiry" }, { href: "/find-manufacturers?help=kitchen", label: "Explore listed shared kitchens" }],
    sources: [sources.development, sources.expert, sources.labels, sources.fda, sources.uf],
  },
  {
    slug: "manufacturer-inquiry-examples",
    title: "What does a useful manufacturer inquiry look like?",
    seoTitle: "Food Manufacturer Inquiry: Example Brief, Email, and Quote",
    description: "Use an annotated fictional product brief, first email, and quote to understand what to share and which questions to ask.",
    eyebrow: "Learn from an example",
    image: guideArtwork("manufacturer-inquiry-examples").src,
    imageAlt: guideArtwork("manufacturer-inquiry-examples").alt,
    directAnswer: "Describe the product, recipe stage, intended package, storage goal, and approximate amount with units. Say what help you need and ask whether the project fits. Keep open questions visible. The examples below are fictional teaching materials, not actual manufacturer quotes or recommended production specifications.",
    whoThisIsFor: "You are preparing a first manufacturer conversation and want to see what the advice looks like in practice.",
    ...dates,
    diagram: "inquiry",
    steps: [{ title: "Use a short product description", text: "Give the recipient enough context to understand what you are trying to make. Your early brief can be useful even with unknowns." }, { title: "Label goals and open decisions", text: "Separate what you have tested from what you hope to achieve. A room-temperature storage goal is not a validated shelf-life claim." }, { title: "Ask a specific fit question", text: "Ask whether the manufacturer handles this product and development stage, and what information it needs next." }, { title: "Review before sharing", text: "Remove private research notes, other suppliers, and unnecessary commercial information. Review the exact recipient and message before sending." }],
    checklist: ["My overview explains the product and recipe stage.", "My planned quantity includes units and is labeled as an estimate.", "My storage and packaging goals are separated from validated specifications.", "My inquiry asks which help is available and what comes next.", "I have reviewed which details I want this recipient to receive."],
    decisions: [{ decision: "What needs to be shared now?", why: "The first message should help the recipient evaluate fit without disclosing unnecessary private detail." }, { decision: "What is the quantity measured in?", why: "Bottles, cases, pounds, and batches cannot be compared without conversion information." }, { decision: "What does the price include?", why: "A filling fee and a complete finished-goods quote cover different work." }],
    definitions: [{ term: "Product brief", meaning: "A concise description of the product and the decisions that matter to a manufacturing conversation." }, { term: "Quote scope", meaning: "The exact work, materials, quantity, and terms included in a price." }, { term: "Open question", meaning: "Something that still needs an answer; it is not a promise or a confirmed requirement." }],
    questions: ["Does this product and development stage fit your services?", "Which information would you need before a trial or project-specific quote?", "Is the minimum per formula, flavor, package, or run?", "Which quoted costs are separate and which are already included?"],
    mistakes: ["Copying a fictional quantity or package as if it were your decision.", "Presenting a storage goal as a validated process.", "Comparing unit prices while ignoring setup, storage, or freight.", "Sending a private founder brief without reviewing the recipient’s version."],
    faq: [{ question: "Are these examples real projects or prices?", answer: "No. They are deliberately fictional examples made for learning. They do not establish manufacturer capabilities, availability, minimums, or market prices." }, { question: "Will saving a checklist contact a manufacturer?", answer: "No. Checklists and cost worksheets are private planning tools. Manufacturer outreach requires its own recipient-specific review and explicit founder action." }],
    directoryHref: "/find-manufacturers?help=production", directoryLabel: "Explore possible manufacturing partners",
    relatedLinks: [{ href: "/guides/what-to-send-a-manufacturer", label: "Decide what to include in your own brief" }, { href: "/guides/first-run-costs", label: "Try your own cost worksheet" }, { href: "/guides/first-manufacturer-call", label: "Prepare for the first call" }],
    sources: [sources.ncsu, sources.uf],
  },
];
