import type { CornerstoneGuide, GuideSource } from "./cornerstones";

const sources = {
  uf: { label: "UF/IFAS Extension: Finding and Using a Co-packer", href: "https://edis.ifas.ufl.edu/publication/FS380" },
  ncsu: { label: "NC State Extension: Choosing and Using a Co-packer", href: "https://content.ces.ncsu.edu/choosing-and-using-a-copacker" },
  msu: { label: "Michigan State Extension: Preparing for High-Volume Food Product Sales", href: "https://www.canr.msu.edu/news/preparing_for_high_volume_food_product_sales_are_you_ready_for_a_co_packer" },
  fdaBusiness: { label: "FDA: How to Start a Food Business", href: "https://www.fda.gov/food/food-industry/how-start-food-business" },
  fdaWater: { label: "FDA: Bottled Water Safety and Manufacturing", href: "https://www.fda.gov/food/buy-store-serve-safe-food/fda-regulates-safety-bottled-water-beverages-including-flavored-water-and-nutrient-added-water" },
  fdaJuice: { label: "FDA: Juice HACCP Questions and Answers", href: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/guidance-industry-questions-and-answers-juice-haccp-regulation" },
  fdaAcid: { label: "FDA: Acidified and Low-Acid Canned Foods", href: "https://www.fda.gov/food/guidance-documents-regulatory-information-topic-food-and-dietary-supplements/acidified-low-acid-canned-foods-guidance-documents-regulatory-information" },
  usdaOrganic: { label: "USDA: Organic Integrity Database", href: "https://organic.ams.usda.gov/integrity/" },
  usdaInspection: { label: "USDA FSIS: Inspected Establishments", href: "https://www.fsis.usda.gov/inspection/establishments" },
  sqf: { label: "SQFI: Find a Certified Site", href: "https://www.sqfi.com/find-a-certified-site" },
} satisfies Record<string, GuideSource>;

type GuideInput = Omit<CornerstoneGuide, "reviewedLabel" | "dateModified">;

function guide(input: GuideInput): CornerstoneGuide {
  return { ...input, reviewedLabel: "25 Aug 2026", datePublished: "2026-08-25", dateModified: "2026-08-25" };
}

export const PRACTICAL_GUIDES: CornerstoneGuide[] = [
  guide({
    slug: "co-packer-vs-private-label",
    title: "Co-packer vs. private label: what is the difference?",
    seoTitle: "Co-Packer vs Private Label for Food and Beverage Brands",
    description: "Compare co-packing, co-manufacturing, and private label in plain language, including formula ownership, preparation, speed, and questions to confirm.",
    eyebrow: "Choose your starting route",
    image: "/images/clay-v2/support/idea-to-product.webp",
    imageAlt: "Clay product idea moving through simple manufacturing stages into packaged goods",
    directAnswer: "A co-packer makes or packages a product for your brand. Private label usually starts with a manufacturer’s existing formula sold under your brand. Co-manufacturing often starts with your formula and written specifications. Companies use these terms differently, so confirm formula ownership, allowed changes, material purchasing, and responsibilities in writing.",
    whoThisIsFor: "This guide is for anyone deciding whether to use an existing manufacturer formula or bring a custom recipe into commercial production.",
    steps: [
      { title: "Choose how much formula control you need", text: "Private label can be a quicker starting point. A custom formula gives you more control but normally needs clearer specifications, trials, and process work." },
      { title: "Ask who owns the formula", text: "Do not assume the label used on a service page answers ownership. Confirm who owns the starting formula, your changes, and the finished version." },
      { title: "Confirm what you may change", text: "Ask whether flavor, sweetness, heat, ingredients, package, or claims can change and what extra development those changes require." },
      { title: "Divide the purchasing work", text: "Write down who buys ingredients, bottles, cans, labels, cases, and freight and who owns leftovers after a run." },
      { title: "Get the agreement in writing", text: "Confirm confidentiality, specifications, approvals, quality expectations, pricing, minimums, and formula terms before committing to production." },
    ],
    checklist: ["Private label or custom goal", "Product and storage description", "Package size and format", "Expected volume and timing", "Changes you want", "Formula-ownership question", "Ingredient and packaging responsibilities", "Buyer certification needs"],
    decisions: [
      { decision: "Manufacturer formula", why: "Usually reduces early development but may limit ownership and customization." },
      { decision: "Your formula", why: "Offers more control but requires specifications, process review, and trials." },
      { decision: "Hybrid approach", why: "Some manufacturers modify an existing base. The contract must explain what you own." },
    ],
    definitions: [
      { term: "Co-packer", meaning: "A manufacturer that makes, fills, packs, or labels products for another brand." },
      { term: "Private label", meaning: "Usually an existing manufacturer product sold under a customer’s brand, subject to the agreement." },
      { term: "Co-manufacturer", meaning: "A manufacturer that may make a customer formula to written specifications. Usage varies by company." },
      { term: "Specification", meaning: "The written requirements for product, package, process, and quality." },
    ],
    questions: ["Who owns the starting formula and any changes?", "What may I customize?", "Who buys ingredients and packaging?", "What is the current minimum for this formula and package?", "What development and trial work is required?", "Which responsibilities will be written into the agreement?"],
    mistakes: ["Assuming every company uses the terms the same way", "Assuming private label includes formula ownership", "Sharing a full recipe before confidentiality is clear", "Choosing only by speed without checking process and package fit"],
    faq: [
      { question: "Is a co-packer the same as a co-manufacturer?", answer: "Sometimes companies use the terms interchangeably. Ask what work the plant performs and who owns the formula instead of relying on the label alone." },
      { question: "Is private label always faster?", answer: "It may be faster when a suitable formula and compatible package already exist, but label work, materials, minimums, and production scheduling still take time." },
      { question: "Can I change a private-label formula?", answer: "Possibly. The manufacturer decides what can change and whether the result becomes custom development. Confirm ownership and added costs in writing." },
    ],
    directoryHref: "/find-manufacturers/wizard",
    directoryLabel: "Match your product to manufacturers",
    sources: [sources.uf, sources.ncsu, sources.msu],
    diagram: "formula",
    relatedLinks: [{ href: "/guides/how-to-find-a-co-packer", label: "How to find a co-packer" }, { href: "/guides/what-to-send-a-manufacturer", label: "What to send a manufacturer" }],
  }),
  guide({
    slug: "how-to-find-a-co-packer",
    title: "How do you find the right co-packer?",
    seoTitle: "How to Find a Co-Packer for Food and Beverages",
    description: "Build a useful brief, search by real product and process fit, compare evidence, and contact a focused shortlist of manufacturers.",
    eyebrow: "Find a manufacturer",
    image: "/images/clay-v2/support/beginner-onboarding.webp",
    imageAlt: "Clay checklist, bottle, jar, can, and question mark for beginning a manufacturer search",
    directAnswer: "Start with a clear product brief, then search for manufacturers that publicly mention your product, process, and package. Make a short list, check each official website, mark missing details as unknown, and ask focused questions. A broad label such as beverage manufacturer does not prove the line fits your formula or volume.",
    whoThisIsFor: "This guide is for people with a food or drink idea who need a practical way to search without emailing every manufacturer they find.",
    steps: [
      { title: "Describe the product", text: "Write the product type, formula path, storage goal, package, expected volume, timing, and required buyer certifications." },
      { title: "Search by disclosed fit", text: "Start with manufacturers that publicly name your product or a compatible process. Unknown does not mean yes." },
      { title: "Check the official website", text: "Confirm that the company currently offers outside manufacturing work and is not only selling its own brand." },
      { title: "Build a small shortlist", text: "Compare three to five realistic options by product, process, package, location, published minimum, and quality requirements." },
      { title: "Send a useful inquiry", text: "Use the same concise brief for each manufacturer and ask only the open questions that matter to fit." },
    ],
    checklist: ["Product type", "Private label or your formula", "Storage goal", "Likely process or open question", "Package and size", "Honest volume", "Launch timing", "Buyer certification needs", "Three to five sourced options"],
    decisions: [
      { decision: "Product fit", why: "A manufacturer should publicly name the product or confirm it directly." },
      { decision: "Process and package fit", why: "The correct product on incompatible equipment is still a poor match." },
      { decision: "Commercial fit", why: "Minimums, location, timing, materials, and storage must work for the project." },
    ],
    definitions: [
      { term: "Official source", meaning: "A current company page, capability sheet, or direct company confirmation." },
      { term: "Shortlist", meaning: "A small group of realistic manufacturers you can compare and contact." },
      { term: "Unknown", meaning: "A detail that is not publicly listed and must be confirmed directly." },
      { term: "Fit", meaning: "Compatibility across product, process, package, volume, quality, and timing." },
    ],
    questions: ["Do you currently accept outside manufacturing projects?", "Does this facility run my product and package?", "What is the current minimum?", "Which process does the line use?", "What should I send for an initial review?", "What is the realistic development and scheduling timeline?"],
    mistakes: ["Treating every directory row as verified", "Assuming a blank field means yes", "Contacting dozens of unrelated plants", "Sending only a product name with no package, volume, or timing"],
    faq: [
      { question: "How many manufacturers should I contact?", answer: "Start with a researched shortlist of three to five. Add more only when the first group is not a technical or commercial fit." },
      { question: "Should I use a directory?", answer: "Yes, for discovery and comparison. Then check current company sources and confirm every important requirement directly." },
      { question: "What if a minimum order is not listed?", answer: "Mark it unknown and ask for the current minimum for your exact product and package. Do not substitute an industry average." },
    ],
    directoryHref: "/find-manufacturers",
    directoryLabel: "Build a manufacturer shortlist",
    sources: [sources.uf, sources.ncsu, sources.msu],
    diagram: "first-run",
    relatedLinks: [{ href: "/guides/co-packer-vs-private-label", label: "Co-packer vs. private label" }, { href: "/guides/what-to-send-a-manufacturer", label: "Prepare your first inquiry" }],
  }),
  guide({
    slug: "what-to-send-a-manufacturer",
    title: "What should you send a food manufacturer?",
    seoTitle: "What to Send a Food or Beverage Manufacturer",
    description: "Prepare a short manufacturer brief with product, formula, process, packaging, volume, timing, and open questions.",
    eyebrow: "Prepare your inquiry",
    image: "/images/clay-v2/support/first-production-run.webp",
    imageAlt: "Clay clipboard, packages, carton, pallet, and measuring tool for production planning",
    directAnswer: "Send a short product brief with what you make, whether you want private label or custom production, the storage goal, package, honest volume, timing, allergens, and required certifications. Include ingredients by weight when appropriate, but agree on confidentiality before sharing a complete proprietary formula. Clearly label anything you do not know yet.",
    whoThisIsFor: "This guide is for anyone preparing a first email, form submission, or introduction request to a food or beverage manufacturer.",
    steps: [
      { title: "Open with the product", text: "Name the food or drink in plain language and say whether you want an existing private-label option or custom production." },
      { title: "Explain storage and process", text: "State refrigerated, frozen, or shelf-stable goals and list any process already set by a qualified expert." },
      { title: "Describe the package", text: "Include container type, size, closure, label style, and whether materials are selected or still flexible." },
      { title: "Give honest numbers", text: "Share your best volume range, timing, and forecast. Say when they are estimates." },
      { title: "Ask the remaining questions", text: "Point out the details you need the manufacturer to confirm instead of hiding uncertainty." },
    ],
    checklist: ["Product name and short description", "Private label or custom", "Ingredients by weight when ready", "Allergens", "Storage goal", "Process status", "Package and size", "Volume range", "Launch window", "Required certifications", "Open questions"],
    decisions: [
      { decision: "One-page brief", why: "Keeps the first review quick while covering the information needed for fit." },
      { decision: "Formula attachment", why: "Share only after confidentiality and the manufacturer’s intake needs are clear." },
      { decision: "Estimate labels", why: "Honest estimates are more useful than false precision." },
    ],
    definitions: [{ term: "Product brief", meaning: "A concise summary used to decide whether a manufacturer may fit." }, { term: "Allergen", meaning: "An ingredient that needs specific labeling and production controls." }, { term: "Forecast", meaning: "Your best estimate of future demand, clearly identified as an estimate." }, { term: "Confidentiality agreement", meaning: "Written terms controlling how private information may be used or shared." }],
    questions: ["Is this enough information for an initial fit review?", "When should I send the full formula?", "Which package details does the line need?", "Which tests or process records are required?", "What is the current minimum?", "What should I expect after submitting the brief?"],
    mistakes: ["Sending only a logo and product name", "Hiding uncertainty behind exact-looking numbers", "Leaving out allergens or storage", "Sending a proprietary formula before confidentiality is clear"],
    faq: [{ question: "Do I need a finished formula before contacting a manufacturer?", answer: "Not for every private-label inquiry. For custom work, you need enough detail for a fit review and should ask when the complete formula is required." }, { question: "Can I say I do not know the process?", answer: "Yes. State the storage goal and what is unknown so the manufacturer can explain what expert or development work comes next." }, { question: "Should I attach a business plan?", answer: "Usually not for the first fit check. Send a concise product brief unless the manufacturer’s intake process asks for more." }],
    directoryHref: "/find-manufacturers/wizard",
    directoryLabel: "Use the matching wizard",
    sources: [sources.uf, sources.ncsu, sources.msu],
    diagram: "first-run",
    relatedLinks: [{ href: "/guides/first-manufacturer-call", label: "Questions for your first call" }, { href: "/guides/first-production-run", label: "Prepare for your first run" }],
  }),
  guide({
    slug: "first-manufacturer-call",
    title: "What should you ask on your first manufacturer call?",
    seoTitle: "Questions for Your First Food Manufacturer Call",
    description: "Use a focused first-call agenda to confirm technical fit, minimums, responsibilities, trials, quality systems, timing, and next steps.",
    eyebrow: "First-call checklist",
    image: "/images/clay-v2/support/question-mark.webp",
    imageAlt: "Clay question mark with product packages for planning a manufacturer conversation",
    directAnswer: "Use the first call to confirm whether the facility, process, package, volume, quality needs, and timing fit your project. Ask who owns each development and purchasing task, what a trial proves, which costs sit outside the quote, and what comes next. Do not try to negotiate every contract term before basic fit is established.",
    whoThisIsFor: "This guide is for people who have a useful product brief and are preparing for an introductory call with a manufacturer.",
    steps: [{ title: "Restate the project", text: "Give a two-minute product, package, storage, volume, and timing summary." }, { title: "Confirm technical fit", text: "Ask about the actual line, process, package, allergens, and product limits." }, { title: "Confirm commercial fit", text: "Ask for the current minimum, development path, deposits, material ownership, and scheduling expectations." }, { title: "Discuss quality evidence", text: "Confirm which regulatory status, food-safety systems, and certifications apply to your facility and product." }, { title: "Close with next steps", text: "Name the documents, samples, owners, and dates required for the next decision." }],
    checklist: ["Product brief open", "Top five fit questions", "Current minimum question", "Trial and testing questions", "Material responsibility question", "Quality and certification scope", "Timeline and next-step owner", "Notes page"],
    decisions: [{ decision: "Technical fit", why: "Must be established before pricing details matter." }, { decision: "Commercial fit", why: "Minimums, cash, timing, and logistics decide whether the project is realistic." }, { decision: "Next decision", why: "A call should end with a clear next step, owner, and needed information." }],
    definitions: [{ term: "Line", meaning: "The connected equipment used to process, fill, close, label, and pack a product." }, { term: "Trial", meaning: "A developmental run that tests the formula, process, or package." }, { term: "Lead time", meaning: "Time required for development, materials, scheduling, and production." }, { term: "Scope", meaning: "The facility, products, processes, and dates covered by a certification or service." }],
    questions: ["Which facility and line would run this product?", "What could make the product incompatible?", "What is the current minimum for this package?", "Who buys each ingredient and packaging item?", "What does the trial prove?", "Which quality systems apply?", "What is the next decision and who owns it?"],
    mistakes: ["Reading a long sales pitch instead of discussing fit", "Asking for price before the package and volume are clear", "Treating company-wide certifications as line-specific", "Ending without written next steps"],
    faq: [{ question: "How long should the first call take?", answer: "Long enough to cover fit and next steps. A focused agenda is more important than a fixed number of minutes." }, { question: "Should I ask for an NDA first?", answer: "Ask about confidentiality before sharing proprietary details. The right timing and document vary by manufacturer." }, { question: "Should I ask for references?", answer: "You can ask about relevant experience and quality evidence, while respecting other customers’ confidentiality." }],
    directoryHref: "/find-manufacturers",
    directoryLabel: "Choose manufacturers to compare",
    sources: [sources.uf, sources.ncsu, sources.msu],
    diagram: "formula",
    relatedLinks: [{ href: "/guides/what-to-send-a-manufacturer", label: "Build your product brief" }, { href: "/guides/food-manufacturing-moqs", label: "Understand minimum orders" }],
  }),
  guide({
    slug: "food-manufacturing-moqs",
    title: "How do food manufacturing minimum orders work?",
    seoTitle: "Food Manufacturing MOQ Explained",
    description: "Understand why minimum orders vary, how to compare published numbers, and how volume, package, process, and materials change a first run.",
    eyebrow: "Minimum orders",
    image: "/images/clay-v2/support/first-production-run.webp",
    imageAlt: "Clay production packages, pallet, clipboard, and carton representing a first manufacturing run",
    directAnswer: "A manufacturing MOQ is the smallest run a manufacturer currently accepts for a particular product, process, and package. It may be stated in units, cases, gallons, pounds, batches, or project dollars. Compare only compatible units, ask what the number includes, and never treat an unpublished minimum as zero or as an industry average.",
    whoThisIsFor: "This guide is for people trying to budget a first run or compare minimums that seem to use completely different units.",
    steps: [{ title: "Get the exact unit", text: "Ask whether the minimum is per SKU, flavor, package, batch, purchase order, or production day." }, { title: "Connect it to the line", text: "The formula, process, container, changeover, and material order quantities can all shape the floor." }, { title: "Convert cautiously", text: "Convert only when package size, yield, and loss assumptions are known. Keep the original published unit visible." }, { title: "Ask what is included", text: "Separate production from trials, testing, ingredients, packaging, storage, freight, and unused materials." }, { title: "Test the business case", text: "Compare the run with cash, realistic demand, shelf life, and available storage." }],
    checklist: ["Minimum unit", "Per SKU or total", "Package size", "Expected yield", "Trial costs", "Ingredient minimums", "Packaging minimums", "Storage capacity", "Shelf life", "Freight plan"],
    decisions: [{ decision: "Manufacturer floor", why: "The line may not run economically below it." }, { decision: "Supplier floor", why: "Ingredients or packaging may require more material than one run uses." }, { decision: "Your safe run size", why: "Demand, cash, shelf life, and storage can be lower than a plant’s floor." }],
    definitions: [{ term: "MOQ", meaning: "Minimum order quantity: the smallest order accepted for a defined product and package." }, { term: "SKU", meaning: "One distinct product, flavor, size, and package combination." }, { term: "Changeover", meaning: "Cleaning and setup required when a line switches products or packages." }, { term: "Yield", meaning: "Usable finished product produced from the planned materials after expected losses." }],
    questions: ["Is the minimum per SKU or across the order?", "Which unit should I use?", "Does the minimum change by package?", "Are trials included?", "What happens to unused materials?", "Which supplier minimums could be larger?"],
    mistakes: ["Comparing gallons with bottles without a verified conversion", "Calling equipment capacity an MOQ", "Assuming unpublished means flexible", "Ignoring cash, shelf life, storage, and freight"],
    faq: [{ question: "What is a typical food manufacturing MOQ?", answer: "There is no reliable universal number. It changes by manufacturer, line, product, package, materials, and schedule." }, { question: "Does a pilot run count as production?", answer: "Not always. Ask whether output is saleable and whether the pilot has a separate minimum and price." }, { question: "Can a minimum be negotiated?", answer: "Sometimes the product or schedule allows flexibility, but the manufacturer must confirm it. Plan from the current quoted floor." }],
    directoryHref: "/find-manufacturers?moq=disclosed",
    directoryLabel: "See manufacturers with published minimums",
    sources: [sources.uf, sources.ncsu, sources.msu],
    diagram: "first-run",
    relatedLinks: [{ href: "/guides/small-moq", label: "See the sourced small-MOQ table" }, { href: "/guides/first-production-run", label: "Plan a first run" }],
  }),
  guide({
    slug: "packaging-formats",
    title: "Which food packaging format should you choose?",
    seoTitle: "Food and Beverage Packaging Formats Explained",
    description: "Compare bottles, cans, jars, pouches, cups, and cartons by process, line compatibility, storage, shipping, and sourcing.",
    eyebrow: "Packaging basics",
    image: "/images/clay-v2/support/idea-to-product.webp",
    imageAlt: "Clay bottles, jars, cans, cartons, and pouches beside simple production equipment",
    directAnswer: "Choose packaging with the product, process, and manufacturer, not as a separate design decision. A bottle, can, jar, pouch, cup, or carton must fit the filling and closing equipment, tolerate processing and storage, protect the product, support labeling, and be available in quantities and lead times your first run can handle.",
    whoThisIsFor: "This guide is for people choosing a first commercial container or checking whether an existing package can run on a manufacturer’s line.",
    steps: [{ title: "Start with product protection", text: "List temperature, pressure, light, oxygen, moisture, refrigeration, and shelf-life needs." }, { title: "Match the process", text: "Confirm whether the container and closure tolerate hot fill, HPP, retort, cold fill, freezing, or another required process." }, { title: "Match the equipment", text: "Check the exact dimensions, fill opening, closure, seam or seal, label area, and case configuration." }, { title: "Check supply", text: "Ask about supplier minimums, lead times, decoration, labels, storage, and ownership of unused packaging." }, { title: "Run a real trial", text: "Test filling, closing, leaking, labeling, case packing, shipping, and finished-product quality." }],
    checklist: ["Container type and size", "Material", "Closure or seal", "Process tolerance", "Line dimensions", "Label method", "Supplier minimum", "Lead time", "Case pack", "Pallet and freight", "Trial plan"],
    decisions: [{ decision: "Rigid package", why: "Bottles, cans, and jars offer structure but require compatible filling and closing equipment." }, { decision: "Flexible package", why: "Pouches and sachets can reduce material and freight but require specific films and sealing systems." }, { decision: "Secondary package", why: "Cartons, trays, and cases affect line equipment, retail presentation, storage, and shipping." }],
    definitions: [{ term: "Primary package", meaning: "The bottle, can, jar, pouch, cup, or other container touching the product." }, { term: "Closure", meaning: "A cap, lid, end, seal, or other part that closes the primary package." }, { term: "Secondary packaging", meaning: "Trays, cartons, cases, and wraps that group primary packages." }, { term: "Line trial", meaning: "A run used to prove the package works on the actual equipment." }],
    questions: ["Can the line run this exact container and closure?", "Does the package tolerate the process?", "Who approves technical drawings and samples?", "What are supplier minimums and lead times?", "Who owns unused packaging?", "How will finished cases ship?"],
    mistakes: ["Buying packaging before line approval", "Choosing from appearance alone", "Ignoring closure and label equipment", "Testing an empty package but not the filled product"],
    faq: [{ question: "Should I choose packaging before finding a manufacturer?", answer: "Bring a preference, but avoid a large purchase until a suitable manufacturer confirms the exact package, closure, process, and line." }, { question: "Can the same bottle work for hot fill and HPP?", answer: "Not automatically. Material, shape, closure, label, and processing conditions must be approved for the actual use." }, { question: "Who usually buys the packaging?", answer: "It varies. Confirm who orders it, pays deposits, stores it, approves it, and owns leftovers." }],
    directoryHref: "/find-manufacturers",
    directoryLabel: "Filter manufacturers by package",
    sources: [sources.uf, sources.ncsu, sources.fdaBusiness],
    diagram: "package",
    relatedLinks: [{ href: "/guides/food-processing-methods", label: "Compare manufacturing processes" }, { href: "/guides/first-production-run", label: "Plan the trial and first run" }],
  }),
  guide({
    slug: "food-processing-methods",
    title: "Hot fill, cold fill, HPP, or retort: which process fits?",
    seoTitle: "Hot Fill vs Cold Fill vs HPP vs Retort",
    description: "Compare four common food and beverage processes by product, storage, package, and the expert validation each project needs.",
    eyebrow: "Process comparison",
    image: "/images/clay-v2/products/juice.webp",
    imageAlt: "Clay juice bottles and fruit representing different commercial processing paths",
    directAnswer: "Hot fill, cold fill, HPP, and retort are different processing paths, not interchangeable labels. The right choice depends on the actual formula, hazards, acidity, package, and storage goal. A qualified process expert and manufacturer should set or confirm the product-specific method. Do not choose a process from category alone.",
    whoThisIsFor: "This guide is for anyone who knows whether a product should be refrigerated or shelf stable but does not yet know the manufacturing term.",
    steps: [{ title: "Set the storage goal", text: "Start with refrigerated, frozen, or shelf-stable distribution." }, { title: "Classify the actual product", text: "Formula, acidity, water activity, particulates, and hazards influence the required controls." }, { title: "Compare suitable processes", text: "Review heat, pressure, fill conditions, package needs, and cold-chain requirements with qualified people." }, { title: "Choose package and process together", text: "The container and closure must survive and support the selected process." }, { title: "Validate before launch", text: "Use the required product-specific review, trial, testing, records, and shelf-life work." }],
    checklist: ["Full formula", "Acidity and other known targets", "Storage goal", "Shelf-life goal", "Package preference", "Particulates and thickness", "Qualified process review", "Line trial", "Distribution plan"],
    decisions: [{ decision: "Hot fill", why: "Often used for suitable high-acid or acidified products in heat-compatible packages." }, { decision: "Cold fill", why: "Describes filling without hot fill; the necessary safety controls and storage still depend on the product." }, { decision: "HPP", why: "Uses high pressure for compatible packaged foods, which commonly remain refrigerated." }, { decision: "Retort", why: "Uses heat after sealing for suitable shelf-stable foods in retort-compatible packages." }],
    definitions: [{ term: "Hot fill", meaning: "Filling a suitable product while hot under a defined process." }, { term: "Cold fill", meaning: "Filling without a hot-fill step; it does not by itself define food safety or shelf life." }, { term: "HPP", meaning: "High pressure processing applied to a compatible packaged product." }, { term: "Retort", meaning: "A scheduled heat process applied after a product is sealed in a compatible package." }],
    questions: ["Who determines the product-specific process?", "What storage condition follows the process?", "Which packages are validated?", "Which tests and records are required?", "Can the line handle thickness and particulates?", "What changes require a new review?"],
    mistakes: ["Treating cold pressed as a complete safety process", "Assuming HPP makes every product shelf stable", "Choosing retort from package appearance", "Buying a container before process approval"],
    faq: [{ question: "Is cold fill the opposite of hot fill?", answer: "It describes a different fill condition, but it does not reveal the complete safety system, preservation method, or storage requirement." }, { question: "Does HPP make food shelf stable?", answer: "HPP products commonly require refrigeration. The validated product, process, package, and storage plan determine the result." }, { question: "Who decides the process?", answer: "The product may require a qualified process authority or other expert, working with the manufacturer and applicable rules." }],
    directoryHref: "/find-manufacturers/wizard",
    directoryLabel: "Match by storage and process",
    sources: [sources.fdaBusiness, sources.fdaJuice, sources.fdaAcid],
    diagram: "storage",
    relatedLinks: [{ href: "/guides/hot-fill", label: "Hot-fill guide" }, { href: "/guides/hpp", label: "HPP guide" }, { href: "/guides/retort", label: "Retort guide" }],
  }),
  guide({
    slug: "food-manufacturing-certifications",
    title: "What do food manufacturing certifications mean?",
    seoTitle: "Food Manufacturing Certifications Explained",
    description: "Separate FDA and USDA status, HACCP and GMP systems, SQF and BRCGS certification, organic and religious certifications, and facility claims.",
    eyebrow: "Trust and quality",
    image: "/images/clay-v2/support/beginner-onboarding.webp",
    imageAlt: "Clay checklist and packaged foods representing manufacturer verification",
    directAnswer: "Food manufacturing terms belong in different groups. FDA registration and USDA inspection are regulatory statuses. HACCP and GMP describe food-safety systems. SQF and BRCGS are third-party certification programs. Organic, kosher, and halal have defined certification scopes. Allergen-free or gluten-free may be facility claims. Confirm the facility, product, scope, and date.",
    whoThisIsFor: "This guide is for founders comparing quality requirements or trying to understand a manufacturer profile without treating every acronym as the same kind of badge.",
    steps: [{ title: "Start with your product", text: "The applicable regulator and required controls depend on what is being made and where it will be sold." }, { title: "Separate regulatory status", text: "FDA registration and USDA inspection are not third-party quality certifications and do not mean FDA approval." }, { title: "Identify food-safety systems", text: "Ask which HACCP plan, GMP program, preventive controls, or other systems apply to the product and line." }, { title: "Verify third-party certification", text: "Check the facility, certification program, scope, and current status for SQF, BRCGS, FSSC 22000, organic, kosher, or halal claims." }, { title: "Test facility claims", text: "Ask what allergen-free, nut-free, or gluten-free means in practice and what controls or certification support it." }],
    checklist: ["Exact facility", "Product and line", "Regulatory status", "Food-safety system", "Third-party scheme", "Certification scope", "Expiration or current status", "Certifier or registry", "Facility claim evidence"],
    decisions: [{ decision: "Regulatory status", why: "Shows which government framework or inspection may apply, not a product endorsement." }, { decision: "Food-safety system", why: "Describes how the manufacturer controls hazards and production practices." }, { decision: "Third-party certification", why: "Shows an audit against a named private standard within a defined scope." }, { decision: "Product or facility certification", why: "Organic, kosher, halal, and similar claims depend on certifier and scope." }],
    definitions: [{ term: "FDA registration", meaning: "A regulatory registration required for many food facilities. It is not FDA approval or certification." }, { term: "USDA inspection", meaning: "Government inspection that applies to defined meat, poultry, and egg-product establishments and operations." }, { term: "HACCP", meaning: "A hazard analysis and critical control point system used for applicable products and processes." }, { term: "SQF or BRCGS", meaning: "Third-party food-safety certification programs with facility and scope details." }],
    questions: ["Which facility does this claim cover?", "Is it registration, inspection, a safety system, or certification?", "Which products and lines are in scope?", "Who issued the certificate?", "Is the status current?", "What does a facility-free claim mean operationally?"],
    mistakes: ["Calling FDA registration FDA approval", "Treating HACCP as the same as SQF", "Using a company-wide claim for every facility", "Assuming a certification applies to every product"],
    faq: [{ question: "Is an FDA-registered facility FDA approved?", answer: "No. Registration is a regulatory status and must not be described as FDA approval or certification." }, { question: "Is HACCP a certification?", answer: "HACCP is a food-safety system. Some organizations audit or certify systems, but the underlying term should not be presented as equivalent to SQF or BRCGS." }, { question: "How do I verify organic or SQF status?", answer: "Use the named certifier or official registry and confirm the exact facility, scope, and current status." }],
    directoryHref: "/find-manufacturers",
    directoryLabel: "Compare published quality information",
    sources: [sources.fdaBusiness, sources.usdaInspection, sources.usdaOrganic, sources.sqf],
    diagram: "formula",
    relatedLinks: [{ href: "/how-we-verify", label: "How The Line List verifies claims" }, { href: "/guides/first-manufacturer-call", label: "What to confirm on a call" }],
  }),
  guide({
    slug: "private-label-bottled-water",
    title: "How do you start a private-label bottled water brand?",
    seoTitle: "Private-Label Bottled Water Manufacturing Guide",
    description: "Choose a water type, bottle, label, run size, quality plan, and private-label bottler without confusing custom labels with custom formulation.",
    eyebrow: "Bottled water guide",
    image: "/images/clay-v2/products/water.webp",
    imageAlt: "Face-free clay water bottles with simple unbranded labels and water-drop props",
    directAnswer: "Private-label bottled water usually starts with a bottler’s existing water and package options, then adds your approved label. First choose the water type, bottle size, case pack, order quantity, delivery area, and timing. Confirm the source, bottling controls, label responsibilities, current minimum, freight, and whether any added flavor or nutrients change the product category.",
    whoThisIsFor: "This guide is for brands, organizations, and retailers comparing custom-label water with a more customized beverage project.",
    steps: [{ title: "Choose the water product", text: "Ask whether the offering is spring, purified, mineral, artesian, sparkling, or another defined water type." }, { title: "Choose from compatible packages", text: "Start with bottle sizes, caps, labels, and case packs the bottler already runs." }, { title: "Prepare label artwork", text: "Follow the bottler’s template and confirm who reviews required statements, source wording, and final proof." }, { title: "Confirm order and freight", text: "Ask for the current minimum, pallet and case configuration, lead time, delivery area, and freight responsibility." }, { title: "Confirm quality evidence", text: "Ask how source and finished water are tested and which facility and regulatory requirements apply." }],
    checklist: ["Water type", "Bottle size", "Cap", "Label template", "Case pack", "Order quantity", "Pallet count", "Delivery address", "Lead time", "Testing and source questions"],
    decisions: [{ decision: "Custom label", why: "Usually uses an existing water and bottle with your artwork." }, { decision: "Custom beverage", why: "Added flavors, nutrients, carbonation, or a custom package can require different formulation and line work." }, { decision: "Freight radius", why: "Water is heavy, so location and delivery terms can materially affect total cost." }],
    definitions: [{ term: "Private label", meaning: "An existing bottler product sold under a customer’s brand according to the agreement." }, { term: "Spring water", meaning: "A defined bottled-water type whose source must meet applicable requirements." }, { term: "Purified water", meaning: "Water treated by a process such as reverse osmosis or distillation and labeled accordingly." }, { term: "Case pack", meaning: "The number and arrangement of bottles packed into one shipping case." }],
    questions: ["What water type and source will appear on the label?", "Which bottles and caps are currently available?", "What is the minimum per label design?", "Who reviews the label?", "How are source and finished water tested?", "What are case, pallet, lead-time, and freight details?"],
    mistakes: ["Assuming custom label means custom formula", "Designing artwork before receiving the template", "Ignoring freight and pallet storage", "Adding ingredients without confirming the process and product rules"],
    faq: [{ question: "Can I put my logo on bottled water?", answer: "Many bottlers offer custom-label programs. You still need to follow their artwork, labeling, order, and approval process." }, { question: "Is there always a large minimum?", answer: "No universal minimum exists. Some programs publish small orders while high-speed bottlers may require much more. Ask for the current number." }, { question: "Can I add electrolytes or flavor?", answer: "Possibly, but that may move the project beyond a standard water-label program. Confirm formulation, processing, labeling, and line requirements." }],
    directoryHref: "/find-manufacturers/water",
    directoryLabel: "Find bottled water manufacturers",
    sources: [sources.fdaWater, sources.fdaBusiness, sources.ncsu],
    diagram: "package",
    relatedLinks: [{ href: "/guides/packaging-formats", label: "Choose a package" }, { href: "/guides/food-manufacturing-moqs", label: "Understand minimum orders" }],
  }),
  guide({
    slug: "fermented-food-manufacturing",
    title: "How do you manufacture a fermented food or drink?",
    seoTitle: "Fermented Food and Beverage Manufacturing Guide",
    description: "Prepare a fermented product for manufacturing by defining the culture, process controls, package, storage, testing, and live-culture goal.",
    eyebrow: "Fermentation guide",
    image: "/images/clay-v2/products/functional-beverages.webp",
    imageAlt: "Face-free clay wellness bottles and fermentation-inspired ingredient props",
    directAnswer: "Commercial fermented products need a repeatable formula, culture and fermentation method, measurable process controls, a compatible package, and a clear refrigerated or shelf-stable plan. Decide whether fermentation should remain active or be stopped, then confirm testing, carbonation or gas management, cold storage, shelf life, and the manufacturer’s experience with that exact product type.",
    whoThisIsFor: "This guide is for founders planning kombucha, fermented drinks, vegetables, sauces, cultured foods, or another food where controlled fermentation shapes the product.",
    steps: [{ title: "Define the target product", text: "Write the ingredients, culture, flavor, acidity, texture, carbonation, alcohol, and live-culture goals." }, { title: "Make fermentation repeatable", text: "Define measurable time, temperature, acidity, handling, and acceptance targets with qualified technical support." }, { title: "Choose what happens after fermentation", text: "Decide whether the product remains active, is chilled, filtered, pasteurized, or otherwise stabilized under a suitable process." }, { title: "Match package and storage", text: "Account for gas, pressure, leakage, oxygen, refrigeration, and continued change during shelf life." }, { title: "Run and monitor a trial", text: "Check safety, flavor, acidity, carbonation, fill, package behavior, storage, and records over the intended life." }],
    checklist: ["Culture and formula", "Fermentation targets", "Acidity measurements", "Alcohol and carbonation questions", "Live-culture goal", "Stabilization plan", "Package pressure fit", "Cold chain", "Testing plan", "Shelf-life plan"],
    decisions: [{ decision: "Active fermentation", why: "May require refrigeration and package controls for continuing gas and product change." }, { decision: "Stabilized product", why: "A validated step may stop or control further fermentation but can change flavor and live cultures." }, { decision: "Alcohol and carbonation", why: "Both can affect licensing, labeling, equipment, package pressure, and monitoring." }],
    definitions: [{ term: "Starter culture", meaning: "Microorganisms used to begin and guide fermentation." }, { term: "Fermentation control", meaning: "Measurable conditions used to keep the process safe and repeatable." }, { term: "Stabilization", meaning: "A suitable process used to control further product change." }, { term: "Cold chain", meaning: "Continuous refrigerated storage and transportation where required." }],
    questions: ["Which fermented products does the facility currently run?", "How are fermentation targets monitored?", "How are alcohol and carbonation controlled?", "Can the package handle the product over shelf life?", "Which testing and records are included?", "What cold storage and freight are available?"],
    mistakes: ["Scaling a time-only kitchen method", "Ignoring continuing fermentation in the package", "Treating every fermented product as the same process", "Launching without cold-chain and shelf-life work"],
    faq: [{ question: "Does every fermented product need refrigeration?", answer: "No single rule covers every product. Formula, process, stabilization, package, and validated shelf-life plan determine storage." }, { question: "Can fermentation continue after packaging?", answer: "Yes for some products, which can change acidity, flavor, alcohol, gas, and package pressure. It must be planned and controlled." }, { question: "Is kombucha manufacturing the same as fermented vegetables?", answer: "No. They may share fermentation concepts, but ingredients, hazards, equipment, packaging, testing, and applicable rules differ." }],
    directoryHref: "/find-manufacturers/fermented-foods",
    directoryLabel: "Find fermented-product manufacturers",
    sources: [sources.fdaBusiness, sources.ncsu, sources.msu],
    diagram: "storage",
    relatedLinks: [{ href: "/guides/food-processing-methods", label: "Compare processing paths" }, { href: "/guides/packaging-formats", label: "Check package compatibility" }],
  }),
  guide({
    slug: "refrigerated-food-manufacturing",
    title: "How do you manufacture a refrigerated food?",
    seoTitle: "Refrigerated Food Manufacturing Guide",
    description: "Plan formulation, food-safety controls, packaging, cold storage, shelf life, freight, and manufacturer fit for refrigerated prepared foods.",
    eyebrow: "Refrigerated food guide",
    image: "/images/clay-v2/products/prepared-refrigerated-foods.webp",
    imageAlt: "Face-free clay refrigerated prepared-food tray with fresh ingredient props",
    directAnswer: "A refrigerated food needs more than a cold label. Define the formula, hazards, validated controls, package, temperature range, shelf-life target, and cold chain from production through delivery. Find a manufacturer that runs the actual product and package, then confirm cooling, environmental controls, testing, storage, freight, and what happens if temperature falls outside the agreed range.",
    whoThisIsFor: "This guide is for founders planning dips, hummus, prepared meals, refrigerated sauces, soups, sides, or other foods intended to stay cold.",
    steps: [{ title: "Define the product and hazards", text: "Document ingredients, allergens, handling, acidity, water activity, particulates, cooking, and post-process exposure." }, { title: "Set the safety process", text: "Work with qualified experts and the manufacturer to define controls, cooling, sanitation, monitoring, and records." }, { title: "Choose a compatible package", text: "Confirm filling temperature, seal, leak resistance, oxygen needs, tamper evidence, label, and case pack." }, { title: "Build the cold chain", text: "Plan cooling, finished-goods storage, refrigerated freight, receiving limits, and temperature monitoring." }, { title: "Validate shelf life", text: "Use appropriate testing and real package conditions to set storage instructions and a defensible shelf life." }],
    checklist: ["Formula and allergens", "Hazard and process review", "Cooling plan", "Package and seal", "Temperature range", "Shelf-life goal", "Testing plan", "Cold storage", "Refrigerated freight", "Receiving and excursion plan"],
    decisions: [{ decision: "Cooked or uncooked", why: "Changes hazards, controls, equipment, and environmental exposure." }, { decision: "Package atmosphere and seal", why: "Affects product protection and shelf life and must fit the line." }, { decision: "Distribution range", why: "Cold storage and freight cost and reliability may limit realistic markets." }],
    definitions: [{ term: "Cold chain", meaning: "The controlled refrigerated path from production through storage, transport, and receiving." }, { term: "Shelf life", meaning: "The supported period a product meets safety and quality requirements under stated conditions." }, { term: "Temperature excursion", meaning: "Time outside the agreed storage or transport temperature range." }, { term: "Environmental monitoring", meaning: "A facility program used to check relevant production areas for environmental hazards." }],
    questions: ["Which refrigerated products and packages run here?", "How is the product cooled and monitored?", "Which environmental controls apply?", "How is shelf life established?", "How much cold storage is available?", "Who arranges refrigerated freight and handles excursions?"],
    mistakes: ["Treating refrigeration as the only food-safety control", "Choosing a package without seal and shelf-life testing", "Scheduling production before cold storage", "Ignoring transit and receiving temperatures"],
    faq: [{ question: "Does refrigeration make a product safe?", answer: "Refrigeration can be one control, but the complete formula, process, sanitation, packaging, handling, and monitoring plan determines safety." }, { question: "Who sets refrigerated shelf life?", answer: "It should be supported by appropriate technical review and testing for the actual product, process, package, and storage conditions." }, { question: "Can a refrigerated product use HPP?", answer: "Some can, when product and package are compatible and the process is validated. HPP is not automatically suitable for every refrigerated food." }],
    directoryHref: "/find-manufacturers/prepared-refrigerated-foods",
    directoryLabel: "Find refrigerated-food manufacturers",
    sources: [sources.fdaBusiness, sources.ncsu, sources.msu],
    diagram: "storage",
    relatedLinks: [{ href: "/guides/hpp", label: "Understand HPP" }, { href: "/guides/first-production-run", label: "Plan the first run" }],
  }),
];
