import { guideArtwork } from "./artwork";
import type { CornerstoneGuide } from "./cornerstones";

const sources = {
  controls: { label: "FDA: Preventive Controls for Human Food", href: "https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-preventive-controls-human-food" },
  allergens: { label: "FDA: Food Allergies", href: "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies" },
  freezing: { label: "USDA FSIS: Freezing and Food Safety", href: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/freezing-and-food-safety" },
  transport: { label: "FDA: Sanitary Transportation of Human and Animal Food", href: "https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-sanitary-transportation-human-and-animal-food" },
  gluten: { label: "FDA: Gluten-Free Labeling of Foods", href: "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/gluten-free-labeling-foods" },
};

// Adapted from the September Drive drafts. Keep changing directory counts and
// manufacturer claims on the canonical category/profile pages, not in articles.
export const PRODUCTION_GUIDES: CornerstoneGuide[] = [
  {
    slug: "dry-blending",
    title: "Dry blending for spices, seasonings, and drink powders",
    seoTitle: "Dry Blending and Powder Co-Packing: First-Run Guide",
    description: "Prepare a spice blend, seasoning mix, or drink powder for manufacturing. Plan formula, blend size, ingredient sourcing, packaging, and your first quote.",
    eyebrow: "Spices and dry mixes",
    image: guideArtwork("dry-blending").src,
    imageAlt: guideArtwork("dry-blending").alt,
    directAnswer: "Dry blending combines measured dry ingredients into a uniform batch before packing. To find a manufacturer, share your formula status, ingredient list, batch size, fill weight, and package direction. Confirm whether the company blends, fills, or does both. A dry product still needs a product-specific food safety review.",
    whoThisIsFor: "First-time makers of spice blends, dry rubs, seasonings, drink powders, soup mixes, and baking mixes. A dry food blend and a dietary supplement can have different requirements; confirm which scope applies before comparing manufacturers.",
    reviewedLabel: "10 Sep 2026",
    datePublished: "2026-09-10",
    dateModified: "2026-09-10",
    diagram: "first-run",
    steps: [
      { title: "Describe the blend and the work you need", text: "Name the product and distinguish mixing ingredients from filling a supplied powder. State whether the formula is a home recipe, a measured draft, or a commercial specification. List the parts that are fixed and the parts you can change." },
      { title: "Put the formula into measurable terms", text: "Bring ingredient weights or percentages, suppliers, and specifications when available. Discuss particle size, density, flow, dust, and clumping with the plant. A fine powder and a large dried herb may need different handling to stay evenly distributed." },
      { title: "Have the safety and allergen needs reviewed", text: "Do not assume that no added water means no hazards. Ask a qualified food-safety professional and the manufacturer to review ingredient hazards, supplier controls, sanitation, allergens, and any necessary testing or treatment. FDA preventive-controls requirements depend on the product and facility." },
      { title: "Choose the package with the filling line", text: "Identify a bulk bag, pouch, jar, shaker, tub, stick pack, or sachet and the target fill weight. Ask the filler to confirm format, material, seal, and label fit before buying packaging. A company that blends your formula may use a separate partner to fill it." },
      { title: "Compare the full first-run quote", text: "Request separate lines for development, ingredients, blending, testing, changeover, filling, packaging, storage, and freight. Ask for the minimum per formula and package, plus the number of batches or SKUs included. Leave unavailable numbers unknown." },
      { title: "Agree on the trial and release criteria", text: "Ask how samples will be taken, how blend uniformity will be assessed, and who approves the finished product. Record formula ownership, ingredient substitutions, lot coding, storage, and the checks needed before shipment." },
    ],
    checklist: ["Product description and formula stage", "Ingredient weights or percentages, if known", "Ingredient suppliers and specifications", "Known allergens and intended label claims", "Target blend weight and number of SKUs", "Package direction and fill weight", "Storage and shelf-life goals for review", "Who buys ingredients, packaging, and labels", "First-run timing and destination", "Open questions clearly marked as unknown"],
    decisions: [
      { decision: "Custom blend or private label", why: "A custom project uses your formula or develops one with the plant. Private label may use an existing blend. Ask what can change and who owns the formula." },
      { decision: "Blending or filling only", why: "A packer may accept finished powder without mixing ingredients. Confirm who blends, samples, fills, seals, and holds the manufacturing records." },
      { decision: "Customer-supplied or plant-sourced ingredients", why: "Material sourcing and supplier approval affect the quote and schedule. Do not send ingredients before the plant accepts them." },
      { decision: "Bulk or retail pack", why: "A large bulk bag and a small stick pack need different filling arrangements. Compare minimums for the actual format." },
    ],
    definitions: [
      { term: "Dry blending", meaning: "Mixing measured dry ingredients into a uniform batch." },
      { term: "Blend uniformity", meaning: "How consistently ingredients are distributed through a batch. Ask how the manufacturer measures it for your formula." },
      { term: "Tolling", meaning: "Manufacturing or packing work using some or all materials supplied by you. Confirm the exact scope in writing." },
      { term: "Stick pack", meaning: "A narrow packet for a small portion, such as drink powder. Confirm the machine and fill range." },
      { term: "Lot code", meaning: "An identifier connecting finished packs to a production batch and its records." },
    ],
    questions: ["Do you blend my formula or only fill a supplied blend?", "Which ingredient specifications and batch weight do you need to assess equipment fit?", "How do you confirm blend uniformity?", "What supplier, allergen, sanitation, and product-testing controls apply?", "Can I supply ingredients or packaging, and what approval is required?", "Which package and fill-weight combinations can this line run?", "Who owns the formula, specifications, samples, and records?", "What is the minimum for this exact formula and package?", "Which costs are separate from the production price?", "What remains unresolved until a trial?"],
    mistakes: ["Treating a dry product as safe solely because no water is added", "Assuming the blender also fills and ships", "Ordering printed film before confirming line fit", "Claiming allergen-free without reviewing cross-contact and labeling", "Comparing a bulk minimum with a retail-unit minimum", "Treating an unfinished formula as a final production specification"],
    faq: [
      { question: "Does dry blending include a kill step?", answer: "The term only describes mixing dry ingredients. Ask whether treatment is needed, where it occurs, and how ingredient and process hazards are controlled. Blending alone does not establish product safety." },
      { question: "Can I use my own ingredients?", answer: "Ask the manufacturer. Some projects use customer-supplied materials, but acceptance, supplier approval, and receiving requirements vary. Get agreement before shipping anything." },
      { question: "What if my formula is not finished?", answer: "Say so in the brief. Ask whether the manufacturer offers formulation, sample work, or a manufacturability review and what those services cost." },
      { question: "How small can my first powder run be?", answer: "There is no universal minimum. Ask for the blend minimum, filling minimum, and packaging purchase separately, with units and any per-SKU conditions." },
    ],
    directoryHref: "/find-manufacturers/spices-dry-mixes",
    directoryLabel: "Compare spice and dry mix manufacturers",
    relatedLinks: [
      { href: "/guides/bakery-manufacturing", label: "Finished bakery versus dry baking mixes" },
      { href: "/guides/packaging-formats", label: "Choose a packaging format" },
      { href: "/guides/food-manufacturing-moqs", label: "Compare manufacturing minimums" },
      { href: "/guides/what-to-send-a-manufacturer", label: "Prepare your manufacturer brief" },
    ],
    sources: [sources.controls, sources.allergens],
  },
  {
    slug: "frozen-food-cold-chain",
    title: "How to prepare a frozen food for manufacturing",
    seoTitle: "Frozen Food Manufacturing and Cold Chain: First-Run Guide",
    description: "Plan a frozen food's first production run, from product and packaging requirements to cooling, freezing, storage, freight, and questions for a co-packer.",
    eyebrow: "Frozen food guide",
    image: guideArtwork("frozen-food-cold-chain").src,
    imageAlt: guideArtwork("frozen-food-cold-chain").alt,
    directAnswer: "To prepare a frozen food for a manufacturer, describe the product, cooked or raw state, package, and first-run volume. Then agree on cooling, freezing, storage, and freight responsibilities. Freezing does not replace a food safety plan: microbes can become active again after thawing, and the finished product still needs appropriate controls.",
    whoThisIsFor: "Founders making frozen meals, dumplings, handhelds, soup, desserts, frozen bakery, or fruit and vegetable packs. If your product is kept cold above freezing, use the refrigerated-food guide instead.",
    reviewedLabel: "10 Sep 2026",
    datePublished: "2026-09-10",
    dateModified: "2026-09-10",
    diagram: "first-run",
    steps: [
      { title: "Define what the customer receives", text: "Write down whether the product is raw, partly cooked, fully cooked, ready to eat after thawing, or intended to cook from frozen. Name ingredients, allergens, portion size, and whether it ships as individual pieces or a filled tray or pouch." },
      { title: "Confirm the facility and food-safety scope", text: "Ask the manufacturer and qualified food-safety support which controls and inspection requirements apply to your exact product. Disclose meat, poultry, and egg ingredients early. Agree on the process review and the evidence required before production." },
      { title: "Plan cooling and freezing as separate steps", text: "If food is cooked, ask how it is cooled before freezing. Have the plant define and record the applicable time and temperature limits, freezing method, and release checks. Confirm the result in a trial instead of copying another product's settings." },
      { title: "Test the product in its real package", text: "Ask whether the package seals, stacks, and protects the food through frozen handling. Review thawed texture and preparation instructions as part of the trial. Shelf-life and storage statements need product-specific support; freezing does not create a universal shelf-life promise." },
      { title: "Assign storage and freight responsibilities", text: "Write down who stores the finished goods, books transport, specifies temperature conditions, checks the shipment, and responds to temperature problems. Ask about storage capacity, fees, included time, and delivery requirements before choosing a run size." },
      { title: "Size the first run to your distribution plan", text: "Compare development, setup, ingredients, packaging, freezing, storage, and freight as separate quote lines. Match the order to the inventory you can store and sell. A lower case price may still mean more cash tied up in frozen stock." },
    ],
    checklist: ["Product description, formula, and allergens", "Raw, partly cooked, fully cooked, or ready-to-eat status", "Meat, poultry, and egg ingredients disclosed", "Individual pieces, tray, pouch, or bulk format", "Target portion and package size", "Cooling and freezing questions for the plant", "Storage and shelf-life goals for validation", "Thawing or cooking instructions for review", "First-run amount and needed date", "Ingredient and packaging ownership", "Frozen storage capacity and cost", "Freight owner and temperature-handling agreement"],
    decisions: [
      { decision: "Frozen or refrigerated", why: "These storage paths have different handling, package, and distribution needs. Confirm the intended finished state before requesting quotes." },
      { decision: "Cook at the plant or after purchase", why: "The product description, process controls, and consumer instructions must agree. Do not leave the cooked state implicit." },
      { decision: "Individual pieces or one filled pack", why: "Discuss how the freezing method and package affect handling, portioning, and the product after thawing." },
      { decision: "On-site or third-party storage", why: "A plant may make the food without holding the whole order. Agree on capacity, fees, and pickup timing." },
    ],
    definitions: [
      { term: "Cold chain", meaning: "The temperature-controlled handling, storage, and transport needed by the product." },
      { term: "Core temperature", meaning: "Temperature inside the food, rather than just the surrounding air. Ask how the plant measures the relevant location." },
      { term: "Freezer burn", meaning: "Dehydration damage that affects frozen-food quality. Package and handling decisions help protect the product." },
      { term: "Release criteria", meaning: "The agreed checks that must pass before a batch can leave the plant." },
    ],
    questions: ["Which frozen products and packages run at this facility?", "How is cooked product cooled before freezing?", "Which freezing method fits this product and portion size?", "What time and temperature limits apply, and how are they recorded?", "What happens if a batch or shipment misses those limits?", "How will the real product and package be evaluated after storage and thawing?", "Who reviews the cooking or thawing instructions?", "What storage capacity and fees apply?", "Who arranges freight and checks temperature conditions?", "What is the minimum for this exact product and package?", "Which development, storage, and freight costs sit outside the production quote?"],
    mistakes: ["Treating freezing as a substitute for food-safety controls", "Promising a shelf life before reviewing the product and package", "Forgetting cooling between cooking and freezing", "Ordering a large run without a storage quote", "Leaving responsibility for temperature failures unclear", "Assuming frozen capacity from a general prepared-food listing"],
    faq: [
      { question: "Does freezing kill all bacteria?", answer: "No. USDA explains that freezing can inactivate microbes, which may become active again after thawing. Food must be safely prepared and handled before freezing and after thawing." },
      { question: "How long will my frozen product last?", answer: "Ask for a shelf-life assessment of your exact formula, process, package, and storage conditions. General freezer-storage guidance is not a commercial shelf-life validation for a new product." },
      { question: "Does a frozen-food co-packer also arrange freight?", answer: "It may, but do not assume so. Agree on storage, pickup, transport conditions, receiving checks, and costs in the quote and shipping plan." },
      { question: "What is the minimum frozen-food order?", answer: "Ask each manufacturer for the minimum per product and package. A directory listing without that number remains unknown. Also compare storage and packaging commitments." },
    ],
    directoryHref: "/find-manufacturers/frozen-foods",
    directoryLabel: "Compare frozen food manufacturers",
    relatedLinks: [
      { href: "/guides/refrigerated-food-manufacturing", label: "Plan a refrigerated product" },
      { href: "/guides/bakery-manufacturing", label: "Prepare frozen dough or baked goods" },
      { href: "/guides/food-manufacturing-moqs", label: "Compare first-run minimums" },
      { href: "/guides/what-to-send-a-manufacturer", label: "Build the product brief" },
    ],
    sources: [sources.freezing, sources.controls, sources.transport],
  },
  {
    slug: "bakery-manufacturing",
    title: "How to prepare a bakery product for a co-packer",
    seoTitle: "Bakery Co-Packing and Baked Goods Manufacturing Guide",
    description: "Prepare cookies, bread, frozen dough, or batter for a bakery manufacturer. Compare production paths, packaging, allergens, trials, and first-run costs.",
    eyebrow: "Bakery and baked goods",
    image: guideArtwork("bakery-manufacturing").src,
    imageAlt: guideArtwork("bakery-manufacturing").alt,
    directAnswer: "A bakery manufacturer needs to know whether you want finished baked goods, frozen dough or batter, or a dry mix. Bring your formula stage, product shape, allergens, package, storage goal, and first-run amount. Confirm the exact steps the plant performs, then agree on trials and product-specific safety and quality checks.",
    whoThisIsFor: "First-product founders making cookies, bread, muffins, cakes, pies, baked bars, dough, or batter. A plant that makes fillings or dry baking mixes does not necessarily bake finished goods. Start with the work your product actually needs.",
    reviewedLabel: "10 Sep 2026",
    datePublished: "2026-09-10",
    dateModified: "2026-09-10",
    diagram: "first-run",
    steps: [
      { title: "Choose finished bake, dough, or mix", text: "Describe the item leaving the plant: finished baked product, partly baked product, frozen dough or batter, or a dry mix baked elsewhere. Specify who does any remaining preparation and how the customer receives the food." },
      { title: "Write down the recipe and production steps", text: "Bring ingredient weights, mixing method, piece size, and known rest, proof, bake, and cooling steps. Include pan or liner details when relevant. Mark unknown settings honestly. A home recipe may need trials on the plant's equipment before becoming a production specification." },
      { title: "Review allergens and intended claims", text: "Disclose every ingredient and intended free-from claim. Discuss allergen cross-contact, cleaning between products, supplier specifications, and label review. FDA's gluten-free labeling criteria are separate from simply omitting wheat; confirm the product and manufacturer's program before making the claim." },
      { title: "Match the bakery line and the package", text: "Ask which mixing, forming, depositing, proofing, baking, cooling, and packing steps the facility performs for similar products. Confirm your portion count, fill weight, bag, tray, clamshell, wrap, or bulk case before ordering materials." },
      { title: "Trial the finished product and storage path", text: "Have the manufacturer and qualified food-safety support review the applicable controls. Assess the real product in its package, including texture and any thawing or finish-bake instructions. An ambient cookie, refrigerated filled item, and frozen dough require different storage and distribution planning." },
      { title: "Compare the complete first-run commitment", text: "Ask for minimums per formula and package, plus development, setup, ingredients, changeovers, packing, storage, and freight. Agree on formula ownership, substitutions, sample approval, and production records. Keep unknown minimums unknown until the plant provides a project-specific quote." },
    ],
    checklist: ["Formula weights or percentages and recipe stage", "Finished bake, partial bake, frozen dough, batter, or dry mix", "Product shape, portion size, and target count", "Known mixing, proofing, baking, and cooling steps", "Pan, liner, or forming needs", "Ingredients, allergens, and proposed label claims", "Package direction and storage goal", "Thawing or finish-bake instructions for review", "Who buys ingredients and packaging", "First-run amount, number of SKUs, and timing", "Trial goals and approval owner", "Unresolved details marked as unknown"],
    decisions: [
      { decision: "Custom formula or private label", why: "Ask whether the plant runs your formula, develops one with you, or offers an existing product under your brand. Confirm ownership and allowed changes." },
      { decision: "Finished bake or bake later", why: "A finished cookie and frozen dough need different equipment, handling, and instructions. Confirm where baking and cooling happen." },
      { decision: "Dry mix or finished bakery", why: "A dry-mix producer may not operate the oven or packing line needed for your baked product. Match the actual steps." },
      { decision: "Ambient, refrigerated, or frozen", why: "The validated product and package determine the storage path. Price the corresponding storage and freight before choosing a run size." },
    ],
    definitions: [
      { term: "Par-bake", meaning: "A partial bake followed by a later finishing step. Confirm preparation and storage instructions for the actual product." },
      { term: "Thaw and serve", meaning: "A product intended to be served after thawing, following its reviewed handling instructions." },
      { term: "Depositing", meaning: "Portioning dough or batter into a shape, pan, liner, or tray using equipment." },
      { term: "Changeover", meaning: "Setup and cleaning between products. Formula, equipment, and allergen differences affect the work." },
      { term: "Private label", meaning: "A product sold under your brand that may use a manufacturer's existing formula. Ask what is customizable or exclusive." },
    ],
    questions: ["Do you make finished baked goods, frozen dough or batter, or dry mixes?", "Which similar bakery products run at this facility today?", "Which recipe, portion size, pan, and process details do you need to quote?", "Who reviews the baking, cooling, and other food-safety controls?", "How do you manage allergen cross-contact and proposed free-from claims?", "Which packaging formats can the line run?", "Can you source materials, or must I supply them?", "How will we assess the product after its intended storage and preparation?", "Who owns the formula, samples, and manufacturing records?", "What is the minimum first run for this exact formula and package?", "Which costs and remaining unknowns must be resolved before production?"],
    mistakes: ["Asking for a cookie quote without a portion size or formula stage", "Assuming every bakery can make bread, laminated pastry, and deposited batter", "Treating baking as the entire food safety plan", "Promising gluten-free or allergen-free claims before review", "Buying packaging before confirming line fit", "Booking frozen production without storage and freight", "Using a minimum for another product as your project's minimum"],
    faq: [
      { question: "Can a co-packer use my home bakery recipe?", answer: "It can be a starting point. Ask whether the plant offers scale-up or development and what trials are needed. Mixing, portioning, baking, and cooling may work differently on production equipment." },
      { question: "Does a bakery listing mean the plant bakes finished products?", answer: "No. A listing may describe dry mixes, batters, fillings, or icings. Check its published products and ask whether the exact facility performs the steps your item needs." },
      { question: "Is wheat-free the same as gluten-free?", answer: "No. FDA has specific criteria for a gluten-free food label. Review the complete formula, ingredients, cross-contact controls, and claim with qualified support." },
      { question: "What is a typical bakery minimum order?", answer: "There is no single reliable minimum across bakery formats. Ask for the current minimum per formula, package, and SKU and check whether packaging purchases create a separate commitment." },
    ],
    directoryHref: "/find-manufacturers/bakery",
    directoryLabel: "Compare bakery and baked goods manufacturers",
    relatedLinks: [
      { href: "/guides/dry-blending", label: "Plan a dry baking mix" },
      { href: "/guides/frozen-food-cold-chain", label: "Plan frozen storage and freight" },
      { href: "/guides/co-packer-vs-private-label", label: "Compare custom and private-label paths" },
      { href: "/guides/first-production-run", label: "Prepare for the first production run" },
    ],
    sources: [sources.controls, sources.allergens, sources.gluten, sources.freezing],
  },
];
