import { Breadcrumbs } from "@/components/Breadcrumbs";
import { NewsletterCta } from "@/components/NewsletterCta";
import { SiteHeader } from "@/components/SiteHeader";
import { pageMetadata } from "@/lib/seo/metadata";
import Link from "next/link";

export const metadata = pageMetadata({ title: "About The Line List", description: "A beginner-friendly directory and learning platform for U.S. food and beverage manufacturing.", path: "/about" });

export default function AboutPage() {
  return <><SiteHeader current="/about" /><main id="main"><article className="prose wrap"><Breadcrumbs items={[{ name: "Home", href: "/" }, { name: "About", href: "/about" }]} /><p className="kicker">About The Line List</p><h1>Manufacturing starts with a product idea</h1><p className="lede">The Line List helps people understand food and beverage manufacturing, compare public manufacturer details, and prepare better questions.</p><div className="split"><section><h2>What you can do here</h2><ul><li>Start with the product you want to make.</li><li>Learn the formula, process, packaging, and storage decisions that shape fit.</li><li>Compare details that manufacturers publish.</li><li>Ask for an introduction after you choose a manufacturer.</li></ul></section><section><h2>What the directory cannot decide</h2><ul><li>Whether a line has current capacity.</li><li>The final process for your formula.</li><li>A manufacturer’s current minimum when it is not published.</li><li>Whether a manufacturer will accept a project.</li></ul></section></div><h2>Why the details stay honest</h2><p>Manufacturer profiles use public source pages. If a minimum, certification, package, or process is not public, we say so. A blank field is not evidence that a capability exists.</p><p>We preserve source links and review dates so you can check the information before making a decision. Read <Link href="/how-we-verify">how verification works</Link>.</p><h2>What “co-packer” means</h2><p>A co-packer is a manufacturer that makes, packages, or labels a product for another brand. Some work with a customer’s formula. Some offer an existing private-label product. The exact service varies, so beginner navigation uses the broader word “manufacturer.”</p><h2>Prepare before you contact a manufacturer</h2><p>A useful request includes the product, formula path, package, storage goal, volume, timing, and open technical questions. The <Link href="/guides/first-production-run">first production run guide</Link> shows how to prepare.</p><div className="profile-actions"><Link className="btn btn-gold" href="/find-manufacturers/wizard">Start matching</Link><Link className="btn btn-ghost" href="/guides">Read the guides</Link></div><p className="claim-compact">Represent a manufacturer? <Link href="/claim-submit">Claim or submit a listing</Link>.</p><NewsletterCta /></article></main></>;
}
