import type { Plant } from "./types";
import { LAST_VERIFIED } from "./types";
import { IMPORTED_PLANTS } from "./imported-plants.generated";

/**
 * Plant-site-verified directory.
 *
 * Source: named plants on the process pages fetched 21 Aug 2026
 * (`linelist-site/hpp.html`, `hot-fill.html`, `retort.html`, `small-moq.html`,
 * `sauce.html`). Overlapping listings are one company record.
 *
 * Do not add rows from `data/copackers.csv`. Blank means unpublished.
 */
const CURATED_PLANTS: Plant[] = [
  {
    slug: "universal-pure",
    name: "Universal Pure",
    sites: [
      { city: "Meriden", state: "CT", note: "Fill+HPP beverage line" },
      { city: "Mira Loma", state: "CA", note: "Fill+HPP beverage line" },
      { city: "Lincoln", state: "NE", note: "HPP + cold chain (toll)" },
      { city: "Villa Rica", state: "GA", note: "HPP + cold chain (toll)" },
      { city: "Arlington", state: "TX", note: "HPP + cold chain (toll)" },
      { city: "Malvern", state: "PA", note: "HPP + cold chain (toll)" },
      { city: "Delphos", state: "OH", note: "HPP + cold chain (toll)" },
    ],
    locationDisplay: "Meriden, CT; Mira Loma, CA (fill+HPP). Also Lincoln, NE; Villa Rica, GA; Arlington, TX; Malvern, PA; Delphos, OH",
    processes: ["hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage", "prepared-rte"],
    packaging: "Beverage: flexible pack, round/square 8–32 oz, cold-fill, non-carbonated. Network HPP also cups, pouches, proteins, dips, wet salads, baby food, pet food (not all filled in-house).",
    productTypesPublished: "Juice and other refrigerated beverages on CT/CA rotary fill; network HPP also proteins, dips, wet salads, baby food, pet food.",
    moqDisplay: "Beverage copack 20,000 bottles/run. Tolling unpublished.",
    publishedSmallMoq: true,
    certs: ["SQF III", "USDA licensed", "FDA approved"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Bottling", href: "https://universalpure.com/beverage-bottling/" },
    extraLinks: [{ label: "Locations", href: "https://universalpure.com/universal-pure-locations/" }],
    overview: [
      "Fill+HPP on the Meriden, CT and Mira Loma, CA beverage lines; other listed sites are HPP plus cold chain (tolling).",
      "Beverage copack is published as flexible pack, round or square 8–32 oz, cold-fill, non-carbonated. Glass and aluminum are not on the beverage copack offer.",
      "Published beverage copack floor is 20,000 bottles/run. Tolling MOQ is unpublished. Organic, kosher, and gluten-free certificates are unpublished.",
    ],
    notes: ["Stay Fresh Foods is omitted as a listing: Universal Pure acquired it 1 Jul 2019; Meriden is now a Universal Pure fill+HPP site."],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Fill+HPP: Meriden, CT; Mira Loma, CA. HPP+cold chain also Lincoln NE, Villa Rica GA, Arlington TX, Malvern PA, Delphos OH (7 sites / 22 machines, vendor).",
        model: "Both. Fill+HPP on CT/CA beverage lines; other sites toll. Vendor claim: “largest independent provider of HPP globally.”",
        formats: "Beverage: flexible pack, round/square 8–32 oz, cold-fill, non-carbonated; Meriden 15-head rotary. Network HPP also cups, pouches, proteins, dips, wet salads, baby food, pet food (not all filled in-house).",
        certs: "SQF III; “USDA licensed and FDA approved.” Organic / kosher / GF: unpublished.",
        moq: "Beverage copack 20,000 bottles/run. Tolling: unpublished.",
        siteLinks: [
          { label: "Bottling", href: "https://universalpure.com/beverage-bottling/" },
          { label: "Locations", href: "https://universalpure.com/universal-pure-locations/" },
        ],
      },
    },
  },
  {
    slug: "maryland-packaging",
    name: "Maryland Packaging",
    sites: [
      { city: "Elkridge", state: "MD" },
      { city: "Halethorpe", state: "MD" },
    ],
    locationDisplay: "Elkridge, MD; Halethorpe, MD",
    processes: ["hpp", "hot-fill", "cold-fill"],
    finderProcesses: ["hpp", "hot-fill"],
    finderProducts: ["beverage", "sauce", "prepared-rte"],
    packaging: "PET, pouches, sachets, tubes; glass listed segregated (not HPP-safe). Hot fill: glass (segregated), PET, LLDPE.",
    productTypesPublished: "Hummus, ranch, salsa, dips, smoothies, teas, cold-brew, juices, RTD, RTE, baby food.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF"],
    lastVerified: LAST_VERIFIED,
    website: { label: "HPP", href: "https://marylandpackaging.com/hpp/" },
    extraLinks: [
      { label: "Copack", href: "https://marylandpackaging.com/landing-pages/food-co-packing-manufacturing-hpp/" },
    ],
    overview: [
      "Fill+HPP at two Maryland plants. The same company also lists hot fill and cold fill.",
      "Published formats include PET, pouches, sachets, and tubes. Glass is listed as segregated and not HPP-safe.",
      "SQF is published (vendor score 98/100). Organic, kosher, halal, and non-GMO are described as available, not a current cert list. MOQ is unpublished.",
    ],
    appearedOn: ["hpp", "hot-fill"],
    guideRows: {
      hpp: {
        location: "Elkridge, MD; Halethorpe, MD. Est. 2003.",
        model: "Fill+HPP (also lists hot fill and cold fill). Vendor: largest HPP facility in the Mid-Atlantic; Avure 10 + two Hiperbaric 525s; up to 6,000 kg/hr.",
        formats: "Hummus, ranch, salsa, dips, smoothies, teas, cold-brew, juices, RTD, RTE, baby food. PET, pouches, sachets, tubes; glass listed segregated (not HPP-safe).",
        certs: "SQF (vendor score 98/100). Organic / kosher / halal / non-GMO described as available, not a current cert list. GF unpublished. USDA vs FDA room: unpublished.",
        moq: "Unpublished",
        siteLinks: [
          { label: "HPP", href: "https://marylandpackaging.com/hpp/" },
          { label: "Copack", href: "https://marylandpackaging.com/landing-pages/food-co-packing-manufacturing-hpp/" },
        ],
      },
      "hot-fill": {
        location: "Elkridge, MD (7030 Troy Hill Dr.) and Halethorpe, MD (3610 Commerce Drive)",
        formats: "Hot fill: glass (segregated), PET, LLDPE. Also cold fill and HPP (separate).",
        certs: "SQF (they claim last inspection 98/100). Organic, Kosher, Halal, Non-GMO listed as certifications they can help a product line obtain — not stated as always-on plant certs.",
        moq: "Unpublished",
        usdaVsFda: "Unpublished",
        organic: "Organic: help-your-line-get-certified language only",
        siteLinks: [
          { label: "marylandpackaging.com", href: "https://marylandpackaging.com/landing-pages/food-co-packing-contract-manufacturing-high-pressure-processing/" },
        ],
      },
    },
  },
  {
    slug: "hpp-food-services",
    name: "HPP Food Services",
    sites: [
      { city: "Buena Park", state: "CA" },
      { city: "Wilmington", state: "CA" },
    ],
    locationDisplay: "Buena Park, CA; Wilmington, CA",
    processes: ["hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage", "prepared-rte"],
    packaging: "PET bottles, spouted pouches, PET/PP cups, foodservice bags.",
    productTypesPublished: "Juices, baby food, dips, meats, RTE.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF Level 2 (Wilmington)", "BRC (Buena Park, Hiperbaric page)"],
    lastVerified: LAST_VERIFIED,
    website: { label: "hppfs.com", href: "https://hppfs.com/" },
    extraLinks: [{ label: "Hiperbaric", href: "https://www.hiperbaric.com/en/hpp-food-services/" }],
    overview: [
      "HPP tolling in Buena Park and Wilmington, CA (ICPK). Buena Park also lists pouching/bottling; Wilmington lists cupping.",
      "hppfs.com does not print the street addresses; the cities are from the Hiperbaric page.",
      "Wilmington SQF Level 2 and Buena Park BRC are published on the Hiperbaric page, not repeated on hppfs.com. Numeric MOQ is unpublished.",
    ],
    notes: ["Hiperbaric is an equipment OEM, not a copacker; its HPP Food Services URL ranks because it is a customer story."],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Buena Park and Wilmington, CA (Hiperbaric page; hppfs.com has no address).",
        model: "Tolling, plus Buena Park pouching/bottling and Wilmington cupping. Hiperbaric: “HPP tolling leader in the greater Los Angeles area.”",
        formats: "Juices, baby food, dips, meats, RTE; PET bottles, spouted pouches, PET/PP cups, foodservice bags.",
        certs: "Wilmington SQF Level 2; Buena Park BRC (Hiperbaric page, not repeated on hppfs.com). Organic / kosher / GF unpublished. FDA/USDA unpublished.",
        moq: "Unpublished",
        siteLinks: [
          { label: "hppfs.com", href: "https://hppfs.com/" },
          { label: "Hiperbaric", href: "https://www.hiperbaric.com/en/hpp-food-services/" },
        ],
      },
    },
  },
  {
    slug: "cal-pack-foods",
    name: "Cal Pack Foods",
    sites: [{ city: "Torrance", state: "CA", note: "22625 S. Western Ave." }],
    locationDisplay: "Torrance, CA",
    processes: ["pack-out", "hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage", "sauce", "prepared-rte"],
    packaging: "Bottling, pouching, cupping.",
    productTypesPublished: "Juice, smoothie, salsa, baby food, wet salads, soups, dressings, purees, dips, sauces.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "calpackfoods.com", href: "https://calpackfoods.com/" },
    overview: [
      "Fills in Torrance, CA, then trucks product in its own refrigerated truck to partner HPP Food Services. Not a vessel owner on the pages fetched.",
      "Published products include juice, smoothie, salsa, baby food, wet salads, soups, dressings, purees, dips, and sauces.",
      "Site says “third-party audited”; named scheme unpublished. “Start small” is not a numeric MOQ.",
    ],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Torrance, CA (22625 S. Western Ave.). 27,000 sq ft (Hiperbaric).",
        model: "Fill, then refrigerated truck to HPP Food Services. Not a vessel owner on pages fetched.",
        formats: "Juice, smoothie, salsa, baby food, wet salads, soups, dressings, purees, dips, sauces. Bottling, pouching, cupping.",
        certs: "“Third-party audited.” Named scheme unpublished.",
        moq: "“Start small” — no number.",
        siteLinks: [{ label: "calpackfoods.com", href: "https://calpackfoods.com/" }],
      },
    },
  },
  {
    slug: "green-plant",
    name: "Green Plant",
    sites: [{ city: "Hialeah", state: "FL", note: "4180 W 104th St, privacy policy" }],
    locationDisplay: "Hialeah, FL",
    processes: ["hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage", "sauce", "prepared-rte"],
    packaging: "Bottles, pouches, jars.",
    productTypesPublished: "Juice, dips, sauces, dressings, RTE meats, seafood, baby food, pet food.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "HPP", href: "https://www.greenplant.com/pages/hpp" },
    extraLinks: [{ label: "Copack", href: "https://www.greenplant.com/pages/co-packing" }],
    overview: [
      "Fill+HPP under one roof and tolling. Hiperbaric datelines Miami; the privacy policy address is Hialeah, FL.",
      "Published formats are bottles, pouches, and jars. Products named include juice, dips, sauces, dressings, RTE meats, seafood, baby food, and pet food.",
      "Own FAQ says “audited standards”; SQF/GFSI is named as a retailer expectation, not a plant cert. “Lower MOQs where possible” is not a number.",
    ],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Hialeah, FL (4180 W 104th St, privacy policy). Hiperbaric datelines Miami.",
        model: "Both. Fill+HPP under one roof and tolling. Hiperbaric vendor: Hiperbaric 420i; “largest toller in Florida”; up to 250,000 lb/day.",
        formats: "Bottles, pouches, jars. Juice, dips, sauces, dressings, RTE meats, seafood, baby food, pet food.",
        certs: "Own FAQ: “audited standards” (SQF/GFSI named as retailer expectation, not a plant cert). Hiperbaric bios: USDA-certified, organic, kosher — treat as secondary.",
        moq: "“Lower MOQs where possible” — no number.",
        siteLinks: [
          { label: "HPP", href: "https://www.greenplant.com/pages/hpp" },
          { label: "Copack", href: "https://www.greenplant.com/pages/co-packing" },
        ],
      },
    },
  },
  {
    slug: "american-pasteurization-company",
    name: "American Pasteurization Company",
    sites: [
      { city: "Milwaukee", state: "WI" },
      { city: "West Sacramento", state: "CA" },
    ],
    locationDisplay: "Milwaukee, WI; West Sacramento, CA",
    processes: ["hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage", "prepared-rte"],
    packaging: "Pouch/bag; squeeze pouch Milwaukee only. Post-HPP sleeve, date code, lidding, kitting.",
    productTypesPublished: "HPP juice and dip tolling; juice fill may be in-house or referred.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF (both sites)"],
    lastVerified: LAST_VERIFIED,
    website: { label: "APC", href: "https://americanpasteurizationcompany.com/" },
    extraLinks: [{ label: "What we do", href: "https://www.americanpasteurizationcompany.com/what-we-do/" }],
    overview: [
      "Pay-as-you-go HPP tolling (claims first US commercial HPP toller, 2004) and on-site co-man at Milwaukee, WI and West Sacramento, CA.",
      "Will not manufacture SKUs that skip HPP. Juice fill may be in-house or referred. Squeeze pouch is Milwaukee only.",
      "SQF is published at both sites. Organic, kosher, and gluten-free are unpublished. Numeric HPP-toll MOQ is unpublished.",
    ],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Milwaukee, WI; West Sacramento, CA.",
        model: "Both. Pay-as-you-go tolling (claims first US commercial HPP toller, 2004) and on-site co-man. Will not manufacture SKUs that skip HPP. Juice fill may be in-house or referred.",
        formats: "Pouch/bag; squeeze pouch Milwaukee only. Post-HPP sleeve, date code, lidding, kitting.",
        certs: "SQF both sites. Organic / kosher / GF unpublished. HACCP for FDA and USDA-regulated customers.",
        moq: "Unpublished",
        siteLinks: [
          { label: "APC", href: "https://americanpasteurizationcompany.com/" },
          { label: "What we do", href: "https://www.americanpasteurizationcompany.com/what-we-do/" },
        ],
      },
    },
  },
  {
    slug: "select-juice",
    name: "Select Juice, LLC",
    sites: [{ city: "Lancaster", state: "PA", note: "1879 Commerce Park East (privacy policy)" }],
    locationDisplay: "Lancaster, PA",
    processes: ["hpp", "hot-fill", "cold-fill", "htst"],
    finderProcesses: ["hpp", "hot-fill"],
    finderProducts: ["beverage"],
    packaging: "Stock PET: 2 / 10 / 12 / 14 oz, 1 L, 2 oz Boston Round; 25 oz HDPE. Glass unpublished.",
    productTypesPublished: "Non-carb juices, NFC, shots, purees, teas.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["USDA Organic", "Non-GMO Verified", "Kosher", "SQF", "FDA-registered", "PA Dept. of Ag GMP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "selectjuice.llc", href: "https://www.selectjuice.llc/" },
    extraLinks: [
      { label: "Copack", href: "https://www.selectjuice.llc/pages/co-pack" },
      { label: "Certifications", href: "https://www.selectjuice.llc/pages/certifications" },
    ],
    overview: [
      "Beverage co-man in Lancaster, PA. HPP is one of four published methods (cold fill, hot fill, HTST, HPP), not a dedicated toller.",
      "Stock PET sizes are published; glass is unpublished. Hot-fill rate is published as 900–1,500 BPH.",
      "USDA Organic, Non-GMO Verified, Kosher, SQF, and FDA-registered are on the plant’s certification page. MOQ is unpublished; the contact page says they will not answer MOQ emails.",
    ],
    appearedOn: ["hpp", "hot-fill"],
    guideRows: {
      hpp: {
        location: "Lancaster, PA (1879 Commerce Park East).",
        model: "Fill + HPP as one of four methods (cold fill, hot fill, HTST, HPP). Beverage co-man, not a dedicated toller.",
        formats: "Non-carb juices, NFC, shots, purees, teas. Stock PET: 2 / 10 / 12 / 14 oz, 1 L, 2 oz Boston Round; 25 oz HDPE.",
        certs: "USDA Organic, Non-GMO Verified, Kosher. SQF / GF unpublished on the HPP fetch. Juice-scope; rooms unlabeled FDA vs USDA.",
        moq: "Unpublished (contact form will not answer MOQ emails).",
        siteLinks: [
          { label: "selectjuice.llc", href: "https://www.selectjuice.llc/" },
          { label: "Copack", href: "https://www.selectjuice.llc/pages/co-pack" },
        ],
      },
      "hot-fill": {
        location: "Lancaster, PA (1879 Commerce Park East on the privacy policy; contact page does not print the street)",
        formats: "Hot fill as a preservation method; 900–1,500 BPH. Stock PET 2/10/12/14 oz, 1 L, 2 oz Boston Round; 25 oz HDPE. Glass: unpublished. Also cold-fill, HTST, HPP.",
        certs: "PA Dept. of Ag GMP; SQF; FDA-registered; USDA Organic; Non-GMO Verified; Kosher",
        moq: "Unpublished. Contact page: they will not answer MOQ/pricing emails.",
        usdaVsFda: "FDA-registered stated. FSIS: unpublished.",
        organic: "USDA Organic stated",
        siteLinks: [
          { label: "Co-pack", href: "https://www.selectjuice.llc/pages/co-pack" },
          { label: "Certs", href: "https://www.selectjuice.llc/pages/certifications" },
        ],
      },
    },
  },
  {
    slug: "youngstown-distributors",
    name: "Youngstown Distributors",
    sites: [{ city: "Reedley", state: "CA" }],
    locationDisplay: "Reedley, CA",
    processes: ["hpp"],
    finderProcesses: ["hpp"],
    finderProducts: ["beverage"],
    packaging: "Bottles 2–32 oz; shrink sleeve / PS; frozen drums; raw and HPP’d bulk.",
    productTypesPublished: "Cold-pressed juices, purees, smoothies.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF Level II"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Cold-pressed juice", href: "https://www.youngstownd.com/cold-pressed-juice" },
    overview: [
      "Fill+HPP under one roof in Reedley, CA (press plus HPP).",
      "Published products are cold-pressed juices, purees, and smoothies; bottles 2–32 oz.",
      "SQF Level II is published. Organic, kosher, and gluten-free are unpublished (“PUR Organics” is a brand name). “Low Minimums” is not a number.",
    ],
    appearedOn: ["hpp"],
    guideRows: {
      hpp: {
        location: "Reedley, CA.",
        model: "Fill+HPP under one roof (press + HPP).",
        formats: "Cold-pressed juices, purees, smoothies; bottles 2–32 oz; shrink sleeve / PS; frozen drums; raw and HPP’d bulk.",
        certs: "SQF Level II. Organic / kosher / GF unpublished (“PUR Organics” is a brand name).",
        moq: "“Low Minimums” — no number.",
        siteLinks: [{ label: "Cold-pressed juice", href: "https://www.youngstownd.com/cold-pressed-juice" }],
      },
    },
  },
  {
    slug: "innomark",
    name: "InnoMark Inc.",
    sites: [{ city: "St. George", state: "UT" }],
    locationDisplay: "St. George, UT",
    processes: ["hot-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["beverage"],
    packaging: "Plastic and glass 8 oz–1 gal; hot-fill aluminum cans.",
    productTypesPublished: "Juices, teas, functional beverages, wellness shots. Also powders (tubs, bags, stick packs, capsules).",
    moqDisplay: "Hot-fill as low as 7,500 liters (FAQ: hot-fill liquid > 7,000 liters; powders > 3,000 kg).",
    publishedSmallMoq: true,
    certs: ["USDA Organic", "Kosher", "FDA-registered", "Utah GMP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "innomarkinc.com", href: "https://innomarkinc.com/" },
    overview: [
      "Hot-fill co-packer in St. George, UT for juices, teas, functional beverages, and wellness shots. Also lists powders.",
      "Does not produce carbonated, high-pH refrigerated, or alcohol products.",
      "Homepage: runs as low as 7,500 liters. FAQ: hot-fill liquid must be larger than 7,000 liters; powders larger than 3,000 kg. USDA Organic and kosher are stated.",
    ],
    appearedOn: ["hot-fill", "small-moq"],
    guideRows: {
      "hot-fill": {
        location: "St. George, UT",
        formats: "Plastic and glass 8 oz–1 gal; hot-fill aluminum cans. Juices, teas, functional beverages, wellness shots. Does not run carbonated, high-pH refrigerated, or alcohol.",
        certs: "USDA Organic; Kosher; private-label FAQ: FDA-registered, Utah GMP",
        moq: "Homepage: as low as 7,500 liters. FAQ: hot-fill liquid > 7,000 liters (powders > 3,000 kg).",
        usdaVsFda: "FDA-registered (private-label FAQ). FSIS: unpublished.",
        organic: "USDA Organic stated",
        siteLinks: [{ label: "innomarkinc.com", href: "https://innomarkinc.com/" }],
      },
      "small-moq": {
        location: "St. George, UT",
        processAsStated: "Hot-fill co-packer: juices, teas, functional beverages, wellness shots, nutritional liquids; also powders (tubs, bags, stick packs, capsules). Hot-fill plastic and glass 8 oz–1 gallon; can handle hot-fill aluminum cans. Does not produce carbonated, high-pH refrigerated, or alcohol.",
        moq: "Hero: “With runs as low as 7,500 liters.” FAQ: “Hot fill Liquid production runs must be larger than 7,000 liters for equipment to function properly. Powders must be larger than 3,000 kgs.” MOQs “affect pricing dramatically but are negotiable.”",
        certs: "USDA Organic certified; Kosher certified (homepage).",
        siteLinks: [{ label: "innomarkinc.com", href: "https://innomarkinc.com/" }],
      },
    },
  },
  {
    slug: "big-brands",
    name: "Big Brands LLC",
    sites: [{ city: null, state: "CA", note: "Southern California / California plants; cities unpublished" }],
    locationDisplay: "Southern California (city unpublished)",
    processes: ["hot-fill", "retort"],
    finderProcesses: ["hot-fill", "retort"],
    finderProducts: ["beverage"],
    packaging: "Hot fill: glass or PET; bottled lines 2–32 oz; pouch hot fill 4 oz–1 gal. Retort: cans 5.5–16 oz (SoCal 8–16 oz); jars 7–32 oz; retortable bowls; stand-up or flat pouches.",
    productTypesPublished: "Hot-fill beverages; retort beverages described as mainly dairy and plant milks (pH greater than 4.5 on their process page).",
    moqDisplay: "Hot fill / bottled: 25,000 units (depending on fill size). Retort: 100K units per SKU.",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Hot fill", href: "https://www.bigbrandsllc.com/hot-fill-beverage-co-packing" },
    extraLinks: [
      { label: "Bottled", href: "https://www.bigbrandsllc.com/bottled-beverage-co-packing" },
      { label: "Retort", href: "https://www.bigbrandsllc.com/retort-beverage-co-packing" },
    ],
    overview: [
      "Multiple US facilities on the homepage; the hot-fill and retort pages name Southern California / California plants. Cities are unpublished.",
      "Hot-fill bottled floor is published as 25,000 units, depending on fill size. The retort page floor is 100K units per SKU — not a hot-fill MOQ.",
      "Homepage lists SQF, GFSI, Organic, Kosher as certification and “ability to meet additional quality standards.” Held cert versus ability to meet is not separated, so those are not treated as verified plant certs here.",
    ],
    notes: ["The company also publishes HPP as a separate process on other pages; it is not on the HPP named-plant shortlist."],
    appearedOn: ["hot-fill", "retort"],
    guideRows: {
      "hot-fill": {
        location: "Southern California plant (city unpublished). Homepage: multiple US facilities. Utah beverage site also lists hot fill.",
        formats: "Glass or PET on the hot-fill page; bottled lines 2–32 oz; pouch hot fill 4 oz–1 gal.",
        certs: "Homepage lists “SQF, GFSI, Organic, Kosher, certification and ability to meet additional quality standards” — held cert vs. “ability to meet” not separated.",
        moq: "Bottled page: 25,000 units, “depending on fill size.” Utah page: majority start at 25,000 MOQ per SKU. Retort page 100k units/SKU is not a hot-fill MOQ.",
        usdaVsFda: "Unpublished (FDA.gov is a footer link, not a registration claim).",
        organic: "Organic listed as a capability, not a named certifier",
        siteLinks: [
          { label: "Hot fill", href: "https://www.bigbrandsllc.com/hot-fill-beverage-co-packing" },
          { label: "Bottled", href: "https://www.bigbrandsllc.com/bottled-beverage-co-packing" },
        ],
      },
      retort: {
        location: "California and Southern California plants (cities unpublished). Homepage: nationwide canning & bottling.",
        formats: "Cans 5.5–16 oz (SoCal 8–16 oz); jars 7–32 oz; retortable bowls; stand-up or flat pouches. SoCal: low-acid retort beverages; glass 8 oz.",
        certs: "Homepage: SQF, GFSI, Organic, Kosher — held cert vs “ability to meet” not separated. Footer FDA.gov is not a registration claim.",
        moq: "Retort page: 100K units per SKU. Bottled-beverage 25,000 units is not a retort MOQ.",
        usdaVsFda: "Unpublished on the retort page",
        organic: "Capability, not a named certifier",
        siteLinks: [
          { label: "Retort", href: "https://www.bigbrandsllc.com/retort-beverage-co-packing" },
          { label: "Process", href: "https://www.bigbrandsllc.com/beverage-copacking-process" },
        ],
      },
    },
  },
  {
    slug: "yoshida-foods",
    name: "Yoshida Foods International",
    sites: [{ city: "Portland", state: "OR" }],
    locationDisplay: "Portland, OR",
    processes: ["hot-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Plastic bottles only; bottled sauces and syrups; bulk totes, drums, pails.",
    productTypesPublished: "Bottled sauces and syrups. No dairy.",
    moqDisplay: "No per-SKU unit MOQ. Inquiry screens for 11,000 gallons/day, at least five times per year.",
    publishedSmallMoq: true,
    certs: ["HACCP", "Kosher Pareve (KOF-K)", "Organic (Oregon Tilth)", "SQF Level 2", "AIB GMP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Hot fill", href: "https://yoshidafoods.com/co-packing-services/hot-fill-co-packing/" },
    extraLinks: [{ label: "Inquiry", href: "https://yoshidafoods.com/inquiry-co-pack/hot-fill-inquiry/" }],
    overview: [
      "Portland, OR hot-fill house for bottled sauces and syrups. Plastic bottles only; no dairy (Kosher Pareve).",
      "Published equipment includes a 32-head filler, 10-head capper, and three 1,500-gal kettles. Bulk totes, drums, and pails are listed.",
      "No per-SKU unit MOQ. The inquiry screens for 11,000 gallons/day, at least five times per year. Omitted from the sauce shortlist table (hot-fill, plastic only, no dairy) but kept here as a named hot-fill plant.",
    ],
    appearedOn: ["hot-fill"],
    guideRows: {
      "hot-fill": {
        location: "Portland, OR",
        formats: "Plastic bottles only; bottled sauces and syrups; bulk totes, drums, pails. 32-head filler, 10-head capper, three 1,500-gal kettles. No dairy.",
        certs: "HACCP; Kosher Pareve (KOF-K); Organic (Oregon Tilth); SQF Level 2; AIB GMP",
        moq: "No per-SKU unit MOQ. Inquiry screens for 11,000 gallons/day, at least five times per year. Typical production day 11,000 gallons; capacity 2 million cases/year.",
        usdaVsFda: "Unpublished",
        organic: "Oregon Tilth stated",
        siteLinks: [
          { label: "Hot fill", href: "https://yoshidafoods.com/co-packing-services/hot-fill-co-packing/" },
          { label: "Inquiry", href: "https://yoshidafoods.com/inquiry-co-pack/hot-fill-inquiry/" },
        ],
      },
    },
  },
  {
    slug: "creative-foodworks",
    name: "Creative Foodworks",
    sites: [{ city: "San Antonio", state: "TX" }],
    locationDisplay: "San Antonio, TX",
    processes: ["hot-fill", "acidified"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Retail 8–32 oz (squeeze bottles, jars, bottles); foodservice 1–50 gallon. Glass and plastic.",
    productTypesPublished: "Hot-filled / acidified sauces, salsas, marinades, dressings, BBQ, hot sauce, queso, pasta sauce, drink mixes.",
    moqDisplay: "1,000 gallon minimum batch; orders placed at least quarterly.",
    publishedSmallMoq: true,
    certs: ["SQF", "Kosher (Orthodox Union)", "Gluten-free (Gluten Free Food Program)"],
    lastVerified: LAST_VERIFIED,
    website: { label: "creativefw.com", href: "https://creativefw.com/" },
    extraLinks: [{ label: "Capabilities", href: "https://creativefw.com/capabilities/" }],
    overview: [
      "San Antonio, TX. Hot-filled and acidified shelf-stable sauces. No own brand. Site: built for brands with real demand, “not first runs.”",
      "Retail 8–32 oz and foodservice 1–50 gallon; glass and plastic.",
      "Published floor is 1,000 gallon, orders at least quarterly. SQF, OU kosher, and Gluten Free Food Program are published.",
    ],
    appearedOn: ["hot-fill", "sauce"],
    guideRows: {
      "hot-fill": {
        location: "San Antonio, TX",
        formats: "Hot-filled / acidified sauces, salsas, marinades, dressings, BBQ, hot sauce, queso, pasta sauce, drink mixes. Retail 8–32 oz (squeeze bottles, jars, bottles); foodservice 1–50 gallon. Glass and plastic.",
        certs: "SQF; Kosher (Orthodox Union); gluten-free (Gluten Free Food Program)",
        moq: "1,000 gallon minimum batch; orders placed at least quarterly. Site: built for brands with real demand, “not first runs.”",
        usdaVsFda: "Unpublished on the pages fetched",
        organic: "Unpublished",
        siteLinks: [
          { label: "creativefw.com", href: "https://creativefw.com/" },
          { label: "Capabilities", href: "https://creativefw.com/capabilities/" },
        ],
      },
      sauce: {
        location: "San Antonio, TX",
        formats: "Hot-filled and acidified shelf-stable. Sauces, salsas, marinades, dressings, BBQ, hot sauce, queso, pasta. Retail 8–32 oz; FS 1–50 gal. Glass and plastic. No own brand.",
        certs: "SQF; Kosher (OU); GF (Gluten Free Food Program)",
        moq: "1,000 gallon; orders at least quarterly. Not first runs.",
        usdaVsFda: "Unpublished",
        organic: "Unpublished",
        siteLinks: [
          { label: "Home", href: "https://creativefw.com/" },
          { label: "Capabilities", href: "https://creativefw.com/capabilities/" },
        ],
      },
    },
  },
  {
    slug: "paradise-food-beverage",
    name: "Paradise Food & Beverage Co.",
    sites: [{ city: "Wilmington", state: "DE" }],
    locationDisplay: "Wilmington, DE",
    processes: ["hot-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["beverage", "sauce"],
    packaging: "Product examples include 16 oz PET, 64 oz HDPE, 16 oz glass.",
    productTypesPublished: "Beverages: juices, lemonades, teas. Sauces: hot sauce, BBQ, dressings, marinades.",
    moqDisplay: "Exact MOQ unpublished. Page: “Typical projects start at 100 units.”",
    publishedSmallMoq: true,
    certs: ["FDA-registered"],
    lastVerified: LAST_VERIFIED,
    website: { label: "myparadisefoods.com", href: "https://myparadisefoods.com/" },
    overview: [
      "Wilmington, DE. Hot-fill: “thermally processed beverages and sauces bottled at temperature.”",
      "Beverages named: juices, lemonades, teas. Sauces named: hot sauce, BBQ, dressings, marinades.",
      "Licensed and FDA-registered. Exact MOQ unpublished; the page says typical projects start at 100 units. Not on the small-MOQ shortlist.",
    ],
    appearedOn: ["hot-fill"],
    guideRows: {
      "hot-fill": {
        location: "Wilmington, DE",
        formats: "Hot-fill: “thermally processed beverages and sauces bottled at temperature.” Beverages: juices, lemonades, teas. Sauces: hot sauce, BBQ, dressings, marinades. Product examples include 16 oz PET, 64 oz HDPE, 16 oz glass.",
        certs: "Licensed, FDA-registered. Additional certifications “can be pursued for specific client programs.”",
        moq: "Exact MOQ unpublished (depends on product/format). Page: “Typical projects start at 100 units.”",
        usdaVsFda: "FDA-registered stated. FSIS: unpublished.",
        organic: "Unpublished",
        siteLinks: [{ label: "myparadisefoods.com", href: "https://myparadisefoods.com/" }],
      },
    },
  },
  {
    slug: "berner-food-beverage",
    name: "Berner Food & Beverage",
    sites: [
      { city: "Dakota", state: "IL" },
      { city: "Rockford", state: "IL", note: "Warehouse" },
    ],
    locationDisplay: "Dakota, IL (warehouse: Rockford, IL)",
    processes: ["retort"],
    finderProcesses: ["retort"],
    finderProducts: ["beverage", "sauce", "prepared-rte"],
    packaging: "Closes jars; suppliers bottles/jars/cans.",
    productTypesPublished: "RTD coffee/tea, dips, sauces, aerosol cheese. Low-acid / high-pH.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF2000 Level III", "Organic certified", "HACCP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Home", href: "https://bernerfoodandbeverage.com/" },
    extraLinks: [{ label: "Make it happen", href: "https://bernerfoodandbeverage.com/build-your-brand/make-it-happen" }],
    overview: [
      "Dakota, IL (copy also: “just outside of Chicago”). Rotary retort plus HTST.",
      "Published products include RTD coffee/tea, dips, sauces, and aerosol cheese. Closes jars.",
      "SQF2000 Level III, organic certified, and HACCP are published. MOQ is unpublished. FSIS is unpublished.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Dakota, IL. Warehouse: Rockford, IL. Copy also: “just outside of Chicago.”",
        formats: "Rotary retort + HTST. RTD coffee/tea, dips, sauces, aerosol cheese. Closes jars; suppliers bottles/jars/cans. Low-acid / high-pH.",
        certs: "SQF2000 Level III; organic certified; HACCP.",
        moq: "Unpublished",
        usdaVsFda: "Private-label: “Registering the product with the FDA.” FSIS: unpublished.",
        organic: "Organic stated",
        siteLinks: [
          { label: "Home", href: "https://bernerfoodandbeverage.com/" },
          { label: "Make it happen", href: "https://bernerfoodandbeverage.com/build-your-brand/make-it-happen" },
        ],
      },
    },
  },
  {
    slug: "walkers-fresh-foods",
    name: "Walker’s Fresh Foods",
    sites: [{ city: "North Kansas City", state: "MO" }],
    locationDisplay: "North Kansas City, MO",
    processes: ["retort", "kettle"],
    finderProcesses: ["retort"],
    finderProducts: ["prepared-rte"],
    packaging: null,
    productTypesPublished: "Specialty RTE. Site shelf life 35–60 days (not ambient sterility).",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["GFSI certified"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-packing", href: "https://walkersfoodproducts.com/co-packing/" },
    extraLinks: [{ label: "Food safety", href: "https://walkersfoodproducts.com/food-safety/" }],
    overview: [
      "North Kansas City, MO. Cold mix, kettle, and retort cooking are named.",
      "Specialty RTE shelf life is published as 35–60 days — not ambient sterility. Retort pack formats are unpublished.",
      "GFSI certified. “Audited and certified by the FDA and USDA”; SQF vs BRC unpublished. “Quantities large or small” is not a number.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "North Kansas City, MO",
        formats: "Cold mix, kettle, retort cooking. Specialty RTE shelf life 35–60 days (not ambient sterility). Retort pack formats: unpublished.",
        certs: "GFSI certified. “Audited and certified by the FDA and USDA”; Costco audits. SQF vs BRC: unpublished.",
        moq: "Unpublished (“quantities large or small”)",
        usdaVsFda: "FDA and USDA named; room split unpublished.",
        organic: "Unpublished",
        siteLinks: [
          { label: "Co-packing", href: "https://walkersfoodproducts.com/co-packing/" },
          { label: "Food safety", href: "https://walkersfoodproducts.com/food-safety/" },
        ],
      },
    },
  },
  {
    slug: "thermal-kitchen",
    name: "Thermal Kitchen",
    sites: [{ city: "Daytona Beach", state: "FL" }],
    locationDisplay: "Daytona Beach, FL",
    processes: ["retort"],
    finderProcesses: ["retort"],
    finderProducts: ["beverage", "sauce", "prepared-rte"],
    packaging: "Spouted pouches 2–16 oz; water-spray, no/minimal particulates.",
    productTypesPublished: "Broths, sauces, baby food, beverages. High-acid: tunnel pasteurization, not retort.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF since 2024", "FDA registered", "USDA inspected"],
    lastVerified: LAST_VERIFIED,
    website: { label: "thermalkitchen.com", href: "https://thermalkitchen.com/" },
    overview: [
      "Daytona Beach, FL. Retort spouted pouches 2–16 oz in a pressurized water-spray vessel. No/minimal particulates.",
      "Named products: broths, sauces, baby food, beverages. High-acid is tunnel pasteurization, not retort.",
      "SQF since 2024; FDA registered; USDA inspected. Organic controls documented; certifier unpublished. MOQ unpublished.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Daytona Beach, FL",
        formats: "Spouted pouches 2–16 oz; water-spray, no/minimal particulates. Broths, sauces, baby food, beverages. High-acid: tunnel pasteurization, not retort.",
        certs: "SQF since 2024; FDA registered; USDA inspected. Organic controls documented.",
        moq: "Unpublished",
        usdaVsFda: "FDA-registered and USDA inspected stated. Rooms: unpublished.",
        organic: "Controls documented; certifier unpublished",
        siteLinks: [{ label: "thermalkitchen.com", href: "https://thermalkitchen.com/" }],
      },
    },
  },
  {
    slug: "sopakco",
    name: "SOPAKCO",
    sites: [
      { city: "Mullins", state: "SC", note: "HQ" },
      { city: "Bennettsville", state: "SC" },
    ],
    locationDisplay: "Mullins, SC; Bennettsville, SC (third US city unpublished)",
    processes: ["retort", "hot-fill"],
    finderProcesses: ["retort", "hot-fill"],
    finderProducts: ["prepared-rte"],
    packaging: "Pouches 2 oz–6 lb; spout pouches; bowls/trays 5–16 oz; meal kits.",
    productTypesPublished: "Retort plus hot-fill plus frozen. Meal kits and pouched meals.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF", "USDA on-site / FSIS"],
    lastVerified: LAST_VERIFIED,
    website: { label: "About", href: "https://sopakco.com/about/" },
    extraLinks: [
      { label: "Pouch", href: "https://sopakco.com/pouch-packaging/" },
      { label: "Bowls/trays", href: "https://sopakco.com/other-packaging/" },
    ],
    overview: [
      "Mullins, SC HQ and Bennettsville, SC. About page: three US facilities — third city unpublished.",
      "Retort, hot-fill, and frozen are named. Pouches 2 oz–6 lb; spout pouches; bowls/trays 5–16 oz; meal kits.",
      "SQF and USDA on-site / FSIS are stated. Kosher, GF, Non-GMO, USDA Organic, and Halal are listed as claims they help you meet — not always-on certs. MOQ unpublished.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Mullins, SC HQ; Bennettsville, SC. About: three US facilities — third city unpublished.",
        formats: "Retort + hot-fill + frozen. Pouches 2 oz–6 lb; spout pouches; bowls/trays 5–16 oz; meal kits.",
        certs: "SQF; USDA on-site / FSIS. Kosher, GF, Non-GMO, USDA Organic, Halal listed as claims they help you meet — not always-on certs.",
        moq: "Unpublished",
        usdaVsFda: "USDA on-site / FSIS stated",
        organic: "Labeling-help language, not a current cert PDF",
        siteLinks: [
          { label: "About", href: "https://sopakco.com/about/" },
          { label: "Pouch", href: "https://sopakco.com/pouch-packaging/" },
          { label: "Bowls/trays", href: "https://sopakco.com/other-packaging/" },
        ],
      },
    },
  },
  {
    slug: "ameriqual-foods",
    name: "AmeriQual Foods",
    sites: [{ city: "Evansville", state: "IN" }],
    locationDisplay: "Evansville, IN",
    processes: ["retort"],
    finderProcesses: ["retort"],
    finderProducts: ["prepared-rte"],
    packaging: "Retort spouted (pre-formed + FFS), pillow (pre-formed + HFFS), gusseted stand-up; rigid containers.",
    productTypesPublished: "Low-acid foods; also DoD / MRE.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF Level 3", "FDA", "HACCP", "USDA–AMS", "USDA–FSIS", "Oregon Tilth"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Contract manufacturing", href: "https://www.ameriqual.com/contract-manufacturing/" },
    extraLinks: [{ label: "About", href: "https://www.ameriqual.com/about-us/" }],
    overview: [
      "Evansville, IN. Retort pouches (spouted, pillow, gusseted stand-up) and rigid containers. Low-acid foods; also DoD / MRE.",
      "On-site thermal process authority is published.",
      "SQF Level 3, FDA, HACCP, USDA–AMS, USDA–FSIS, and Oregon Tilth are stated. MOQ unpublished.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Evansville, IN",
        formats: "Retort spouted (pre-formed + FFS), pillow (pre-formed + HFFS), gusseted stand-up; rigid containers. Low-acid foods; also DoD / MRE.",
        certs: "SQF Level 3; FDA; HACCP; USDA–AMS; USDA–FSIS; Oregon Tilth; on-site TPA.",
        moq: "Unpublished",
        usdaVsFda: "FDA and USDA–FSIS stated",
        organic: "Oregon Tilth stated",
        siteLinks: [
          { label: "Contract manufacturing", href: "https://www.ameriqual.com/contract-manufacturing/" },
          { label: "About", href: "https://www.ameriqual.com/about-us/" },
        ],
      },
    },
  },
  {
    slug: "select-brands",
    name: "Select Brands, LLC",
    sites: [{ city: "Springfield", state: "MO" }],
    locationDisplay: "Springfield, MO",
    processes: ["retort", "hot-fill"],
    finderProcesses: ["retort", "hot-fill"],
    finderProducts: ["prepared-rte"],
    packaging: "Gusseted 6–16 oz; spouted 3–16 oz; pillow 4–40 oz.",
    productTypesPublished: "Broth, soups, entrees, “USDA products.” Low- and high-acid.",
    moqDisplay: "Minimum unpublished. Runs can range from 10,000 to over 100,000 pouches.",
    publishedSmallMoq: false,
    certs: ["USDA/FDA registered", "SQF", "BSCI"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Capabilities", href: "https://www.select-brands.net/manufacturing-capabilities/" },
    extraLinks: [{ label: "Quality", href: "https://www.select-brands.net/quality-compliance/" }],
    overview: [
      "Springfield, MO. Retort and hot fill (low- and high-acid). Gusseted, spouted, and pillow pouches with published size bands.",
      "Named products: broth, soups, entrees, “USDA products.”",
      "Minimum unpublished. Site says runs can range from 10,000 to over 100,000 pouches, and “smaller minimum orders” with no number. USDA Organic, Non-GMO, and GFCO are offered upon request.",
    ],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Springfield, MO",
        formats: "Retort + hot fill (low- and high-acid). Gusseted 6–16 oz; spouted 3–16 oz; pillow 4–40 oz. Broth, soups, entrees, “USDA products.”",
        certs: "USDA/FDA registered; SQF; BSCI. Offered: USDA Organic, Non-GMO, GFCO / Whole Grain “upon request.”",
        moq: "Minimum unpublished. Runs “can range from 10,000 to over 100,000 pouches.” “Smaller minimum orders” — no number.",
        usdaVsFda: "USDA/FDA registered. “USDA products” is a category, not a room map.",
        organic: "USDA Organic offered",
        siteLinks: [
          { label: "Capabilities", href: "https://www.select-brands.net/manufacturing-capabilities/" },
          { label: "Quality", href: "https://www.select-brands.net/quality-compliance/" },
        ],
      },
    },
  },
  {
    slug: "baxters-north-america",
    name: "Baxters North America",
    sites: [
      { city: "Salem", state: "OR" },
      { city: "East Bernstadt", state: "KY" },
      { city: "Cincinnati", state: "OH", note: "HQ" },
    ],
    locationDisplay: "Salem, OR; East Bernstadt, KY (HQ: Cincinnati, OH)",
    processes: ["retort"],
    finderProcesses: ["retort"],
    finderProducts: ["prepared-rte"],
    packaging: "Pillow / stand-up / HFFS / fitment / large spouted; bowls/trays/cups.",
    productTypesPublished: "Shelf-stable RTE and frozen.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF Level 3 Certified", "HACCP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Capabilities", href: "https://baxtersna.com/contract-manufacturing/capabilities/" },
    extraLinks: [
      { label: "Packaging", href: "https://baxtersna.com/contract-manufacturing/packaging-formats/" },
      { label: "Quality", href: "https://baxtersna.com/why-baxters/quality-safety/" },
    ],
    overview: [
      "Salem, OR and East Bernstadt, KY; HQ Cincinnati, OH. Formerly Truitt Bros as a standalone listing.",
      "Static and rotational retorts. Pillow / stand-up / HFFS / fitment / large spouted pouches; bowls, trays, cups. Shelf-stable RTE and frozen.",
      "SQF Level 3 Certified; HACCP; TPA on staff. MOQ unpublished. Organic certifier unpublished.",
    ],
    notes: ["Truitt Bros is omitted as a standalone listing: now Baxters North America."],
    appearedOn: ["retort"],
    guideRows: {
      retort: {
        location: "Salem, OR; East Bernstadt, KY. HQ: Cincinnati, OH",
        formats: "Static and rotational retorts. Pillow / stand-up / HFFS / fitment / large spouted; bowls/trays/cups. Shelf-stable RTE and frozen.",
        certs: "SQF Level 3 Certified; HACCP; TPA on staff. Capabilities page also says SQF Level 3 approved vendors and “Compliant for HACCP, FDA, USDA, and Organic.”",
        moq: "Unpublished",
        usdaVsFda: "FDA and USDA as compliance; rooms unpublished",
        organic: "Compliance language; certifier unpublished",
        siteLinks: [
          { label: "Capabilities", href: "https://baxtersna.com/contract-manufacturing/capabilities/" },
          { label: "Packaging", href: "https://baxtersna.com/contract-manufacturing/packaging-formats/" },
          { label: "Quality", href: "https://baxtersna.com/why-baxters/quality-safety/" },
        ],
      },
    },
  },
  {
    slug: "minimus-products",
    name: "Minimus Products",
    sites: [{ city: "Newbury Park", state: "CA" }],
    locationDisplay: "Newbury Park, CA",
    processes: ["pack-out"],
    finderProcesses: [],
    finderProducts: ["beverage"],
    packaging: "Bags, packets/sachets, stick packs, bottles, sprayers, jars, cans.",
    productTypesPublished: "Food, beverage, supplements, personal care. Does not hot-fill, pasteurize, or run aseptic.",
    moqDisplay: "Projects start at $2,500.",
    publishedSmallMoq: true,
    certs: [
      "FDA-registered food packaging facility",
      "CA Dept. of Health certified for food and organic food packaging",
      "CCOF organic",
      "OK kosher",
    ],
    lastVerified: LAST_VERIFIED,
    website: { label: "minimusproducts.biz", href: "https://minimusproducts.biz/" },
    extraLinks: [{ label: "FAQ", href: "https://minimusproducts.biz/faq/" }],
    overview: [
      "Newbury Park, CA pack-out house. Bags, packets/sachets, stick packs, bottles, sprayers, jars, cans.",
      "Does not hot-fill, pasteurize, or run aseptic. Not USDA for dairy, poultry, beef, pork, eggs, or baby formula (FAQ).",
      "Published floor is $2,500 per project.",
    ],
    appearedOn: ["small-moq"],
    guideRows: {
      "small-moq": {
        location: "Newbury Park, CA",
        processAsStated: "Filling/pack-out: bags, packets/sachets, stick packs, bottles, sprayers, jars, cans. Food, beverage, supplements, personal care. Does not hot-fill, pasteurize, or run aseptic.",
        moq: "“Projects start at $2,500.” Also: “Low job minimum: $2500.” FAQ: “What is your minimum run? It is $2500 for a given project.”",
        certs: "FDA-registered food packaging facility; CA Dept. of Health certified for food and organic food packaging; CCOF organic; OK kosher. Not USDA for dairy/poultry/beef/pork/eggs/baby formula (FAQ).",
        siteLinks: [{ label: "minimusproducts.biz", href: "https://minimusproducts.biz/" }],
      },
    },
  },
  {
    slug: "ibr-packaging",
    name: "IBR Packaging",
    sites: [{ city: "Carrollton", state: "TX" }],
    locationDisplay: "Carrollton, TX",
    processes: ["pack-out"],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: "Sachets, pouches, stick packs, premade bags.",
    productTypesPublished: "Liquids/wet (hot sauce, dressings, syrups, oils), dry powders/seasonings, granular.",
    moqDisplay: "Regularly run orders as small as 5,000 units.",
    publishedSmallMoq: true,
    certs: ["FDA-registered", "SQF Level 2"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Food", href: "https://ibrpackaging.com/industries/food/" },
    overview: [
      "Carrollton, TX. Food into sachets, pouches, stick packs, and premade bags. Operating since 2012.",
      "Liquids/wet named: hot sauce, dressings, syrups, oils. Also dry powders/seasonings and granular.",
      "Published language: regularly run orders as small as 5,000 units. FDA-registered; SQF Level 2. Allergen handling “case-by-case.”",
    ],
    appearedOn: ["small-moq"],
    guideRows: {
      "small-moq": {
        location: "Carrollton, TX",
        processAsStated: "Food into sachets, pouches, stick packs, premade bags. Liquids/wet (hot sauce, dressings, syrups, oils), dry powders/seasonings, granular.",
        moq: "“Minimums vary by product and packaging format, but we regularly run orders as small as 5,000 units.” Same 5,000-unit pilot language on the how-it-works page.",
        certs: "FDA-registered; SQF Level 2. Operating since 2012. Allergen handling “case-by-case.”",
        siteLinks: [{ label: "ibrpackaging.com/industries/food", href: "https://ibrpackaging.com/industries/food/" }],
      },
    },
  },
  {
    slug: "parish-foods",
    name: "Parish Foods",
    sites: [{ city: null, state: "LA", note: "City unpublished on site" }],
    locationDisplay: "Louisiana (city unpublished)",
    processes: ["hot-fill", "cold-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Plastic and glass; cups, bottles, gallons, 5-gallon pails. Bottles 1–32 oz; cups 1.5–3 oz. No square/flask.",
    productTypesPublished: "Hot fill or cold fill sauces/dressings; dry seasonings, rubs, batters, mixes.",
    moqDisplay: "Cups/gallons 25 gal; retail bottled sauces 50 gal; bulk spices/batters/dry mixes 50 lb; retail spice containers 20 cases (12 pack).",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-packing", href: "https://parishfoods.com/pages/co-packing" },
    overview: [
      "Louisiana; city unpublished on the plant site. Hot fill or cold fill sauces and dressings; also dry seasonings, rubs, batters, mixes.",
      "Plastic and glass; cups, bottles, gallons, 5-gallon pails. No square/flask.",
      "Published floors: 25 gallons (cups or gallons), 50 gallons retail bottled sauces. Site also says they want a long-term manufacturing partner, not a one-time test run. No SQF/BRC/organic/kosher badge on the pages fetched.",
    ],
    appearedOn: ["small-moq", "sauce"],
    guideRows: {
      "small-moq": {
        location: "Louisiana (city unpublished on site)",
        processAsStated: "Hot fill or cold fill sauces/dressings; dry seasonings, rubs, batters, mixes. Plastic and glass; cups, bottles, gallons, 5-gallon pails.",
        moq: "Per production run: bulk spices/batters/dry mixes 50 lb; retail spice containers 20 cases (12 pack); sauces in cups or gallons 25 gallons; retail bottled sauces 50 gallons. Site also says they want a “long-term manufacturing partner, not a one-time test run.”",
        certs: "FDA and Louisiana labeling/registration language on site. No SQF/BRC/organic/kosher badge published on the pages fetched.",
        siteLinks: [{ label: "parishfoods.com/pages/co-packing", href: "https://parishfoods.com/pages/co-packing" }],
      },
      sauce: {
        location: "Louisiana (city unpublished)",
        formats: "Hot fill or cold fill sauces/dressings; plastic and glass. Bottles 1–32 oz; cups 1.5–3 oz; gallons; 5-gal pails. No square/flask.",
        certs: "FDA and Louisiana registration/label language. SQF unpublished.",
        moq: "Cups/gallons 25 gal; retail bottled 50 gal. Not a one-time test run.",
        usdaVsFda: "FDA-registration language. FSIS unpublished.",
        organic: "Unpublished",
        siteLinks: [{ label: "Co-packing", href: "https://parishfoods.com/pages/co-packing" }],
      },
    },
  },
  {
    slug: "copacking-express",
    name: "Co-Packing Express",
    sites: [{ city: "St. Petersburg", state: "FL" }],
    locationDisplay: "St. Petersburg, FL",
    processes: ["pack-out"],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: null,
    productTypesPublished: "Liquids (filling/bottling) and dry spices/powders.",
    moqDisplay: "Liquids 100 gallons per run; dry 400 pounds per run. Test batches priced $2,500–$3,000.",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "MOQ", href: "https://copackingexpress.com/co-packing-minimum-order-quantity/" },
    extraLinks: [{ label: "Contact", href: "https://copackingexpress.com/contact-us/" }],
    overview: [
      "St. Petersburg, FL. Liquids (filling/bottling) and dry spices/powders.",
      "Claims support for FDA scheduled-process filing on acidified/low-acid products — confirm in diligence, not from this card.",
      "Published floors: liquids 100 gallons per run; dry 400 pounds per run. Test batches priced $2,500–$3,000. Self-describes as FDA 21 CFR Part 117 (cGMP) and HACCP-compliant; no SQF/organic/kosher published.",
    ],
    notes: ["Omitted from the sauce shortlist table (100 gal liquid) but kept here as a named small-MOQ plant."],
    appearedOn: ["small-moq"],
    guideRows: {
      "small-moq": {
        location: "St. Petersburg, FL",
        processAsStated: "Liquids (filling/bottling) and dry spices/powders. Claims support for FDA scheduled-process filing on acidified/low-acid products — confirm in diligence, not from this table.",
        moq: "Liquids 100 gallons per run; dry 400 pounds per run. Test batches priced $2,500–$3,000.",
        certs: "Self-describes as FDA 21 CFR Part 117 (cGMP) and HACCP-compliant. No SQF/organic/kosher published on the pages fetched.",
        siteLinks: [{ label: "copackingexpress.com", href: "https://copackingexpress.com/co-packing-minimum-order-quantity/" }],
      },
    },
  },
  {
    slug: "precision-pack-partners",
    name: "Precision Pack Partners",
    sites: [{ city: "Orem", state: "UT" }],
    locationDisplay: "Orem, UT",
    processes: ["pack-out"],
    finderProcesses: [],
    finderProducts: [],
    packaging: "Liquid spout-pouch filling. Pouch sizes 20–500 ml; viscosity “free-flowing liquids to higher-viscosity gels & purees.”",
    productTypesPublished: "Liquid spout-pouch filling; free-flowing liquids to higher-viscosity gels & purees. Homepage does not name beverage, sauce, or RTE.",
    moqDisplay: "MOQs start as low as 250 units.",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "precisionpackpartners.com", href: "https://www.precisionpackpartners.com/" },
    overview: [
      "Orem, UT. Liquid spout-pouch filling. “Give us the ingredients, we’ll give you product.”",
      "Published pouch sizes 20–500 ml. A pouch-line floor, not a thermal MOQ.",
      "“MOQs start as low as 250 units.” “FDA-compliant” / “certified facility” as published; no SQF, organic, or kosher claim found on the homepage.",
    ],
    appearedOn: ["small-moq"],
    guideRows: {
      "small-moq": {
        location: "Orem, UT",
        processAsStated: "Liquid spout-pouch filling. “Give us the ingredients, we’ll give you product.” Pouch sizes 20–500 ml; viscosity “free-flowing liquids to higher-viscosity gels & purees.”",
        moq: "“MOQs start as low as 250 units.” Also: “Test market viability with 250 units.”",
        certs: "“FDA-compliant” / “certified facility” as published. No SQF, organic, or kosher claim found on the homepage.",
        siteLinks: [{ label: "precisionpackpartners.com", href: "https://www.precisionpackpartners.com/" }],
      },
    },
  },
  {
    slug: "chelten-house",
    name: "Chelten House",
    sites: [{ city: null, state: "NJ", note: "City unpublished" }],
    locationDisplay: "New Jersey (city unpublished)",
    processes: [],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: "Foodservice 8–64 oz pouch/container, shelf-stable. Fill method unpublished.",
    productTypesPublished: "Dressings, pasta/pizza, salsa, BBQ, ketchup, marinades, simmer/international; private label names hot sauce.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF 2000 Level 3", "HACCP"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-man", href: "https://cheltenhouse.com/co-manufacturing/" },
    extraLinks: [{ label: "QA", href: "https://cheltenhouse.com/quality-assurance-and-food-safety/" }],
    overview: [
      "New Jersey; city unpublished. Large-scale co-man. Nine lines; 500k+ sq ft.",
      "Named products: dressings, pasta/pizza, salsa, BBQ, ketchup, marinades, simmer/international; private label names hot sauce. Fill method unpublished.",
      "SQF 2000 Level 3 and HACCP. MOQ unpublished — not a small-MOQ plant. Organic products “35+ years”; certifier unpublished.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "New Jersey (city unpublished)",
        formats: "Large-scale co-man. Nine lines; 500k+ sq ft. Dressings, pasta/pizza, salsa, BBQ, ketchup, marinades, simmer/international; private label names hot sauce. FS 8–64 oz pouch/container, shelf-stable. Fill method unpublished.",
        certs: "SQF 2000 Level 3; HACCP",
        moq: "Unpublished. Not a small-MOQ plant.",
        usdaVsFda: "Unpublished",
        organic: "Organic products 35+ years. Certifier unpublished.",
        siteLinks: [
          { label: "Co-man", href: "https://cheltenhouse.com/co-manufacturing/" },
          { label: "QA", href: "https://cheltenhouse.com/quality-assurance-and-food-safety/" },
        ],
      },
    },
  },
  {
    slug: "supreme-cuisine",
    name: "Supreme Cuisine",
    sites: [{ city: "Montgomery City", state: "MO" }],
    locationDisplay: "Montgomery City, MO",
    processes: ["hot-fill", "cold-fill", "retort"],
    finderProcesses: ["hot-fill", "retort"],
    finderProducts: ["sauce", "prepared-rte"],
    packaging: "Glass and plastic. Cups 1–4 oz through totes 250–300 gal.",
    productTypesPublished: "Sauces, dressings, broths, sous vide meats.",
    moqDisplay: "Minimum runs starting at 1,000 gallons.",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Bottling", href: "https://supremecuisine.com/bottling/" },
    overview: [
      "Montgomery City, MO. Sauces, dressings, broths, sous vide meats. Hot fill, cold fill, retort.",
      "Glass and plastic. Cups 1–4 oz through totes 250–300 gal.",
      "Minimum runs starting at 1,000 gallons. FDA- and USDA-inspected; meat-sauce room unpublished. SQF, Organic, Non-GMO, Gluten Free Certified appear as one bullet — held vs capability not separated.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Montgomery City, MO",
        formats: "Sauces, dressings, broths, sous vide meats. Hot fill, cold fill, retort. Glass and plastic. Cups 1–4 oz through totes 250–300 gal.",
        certs: "SQF, Organic, Non-GMO, Gluten Free Certified as one bullet — held vs. capability not separated.",
        moq: "Minimum runs starting at 1,000 gallons.",
        usdaVsFda: "FDA- and USDA-inspected. Meat-sauce room unpublished.",
        organic: "Same certified bullet",
        siteLinks: [{ label: "Bottling", href: "https://supremecuisine.com/bottling/" }],
      },
    },
  },
  {
    slug: "stir-foods",
    name: "Stir Foods",
    sites: [
      { city: "Orange", state: "CA" },
      { city: "Fullerton", state: "CA" },
    ],
    locationDisplay: "Orange, CA; Fullerton, CA",
    processes: ["kettle", "hot-fill", "cold-fill", "retort", "aseptic"],
    finderProcesses: ["hot-fill", "retort"],
    finderProducts: ["sauce"],
    packaging: "Pouch/cup/bag/bulk; glass, plastic, cups, totes, drums.",
    productTypesPublished: "Sauces, dressings, dips.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF Level 3 HACCP", "FDA and USDA inspected"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Custom sauce", href: "https://www.stirfoods.com/custom-sauce-manufacturer" },
    extraLinks: [{ label: "Partner", href: "https://www.stirfoods.com/partner" }],
    overview: [
      "Orange, CA and Fullerton, CA. Mississauga, ON is not a US listing.",
      "Kettle; hot and cold fill; retort; emulsification; aseptic and non-aseptic. Sauces, dressings, dips.",
      "SQF Level 3 HACCP; FDA and USDA inspected. Rooms unpublished. MOQ unpublished — not a small-MOQ plant.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Orange, CA; Fullerton, CA. Mississauga, ON not US.",
        formats: "Sauces, dressings, dips. Kettle; hot & cold fill; retort; emulsification; aseptic & non-aseptic. Pouch/cup/bag/bulk; glass, plastic, cups, totes, drums.",
        certs: "SQF Level 3 HACCP; FDA and USDA inspected",
        moq: "Unpublished. Not a small-MOQ plant.",
        usdaVsFda: "FDA and USDA inspected. Rooms unpublished.",
        organic: "Claims-review only. Certifier unpublished.",
        siteLinks: [
          { label: "Custom sauce", href: "https://www.stirfoods.com/custom-sauce-manufacturer" },
          { label: "Partner", href: "https://www.stirfoods.com/partner" },
        ],
      },
    },
  },
  {
    slug: "tulkoff",
    name: "Tulkoff Food Products",
    sites: [
      { city: "Baltimore", state: "MD" },
      { city: "Cincinnati", state: "OH" },
    ],
    locationDisplay: "Baltimore, MD; Cincinnati, OH",
    processes: [],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: "Glass/plastic; VFFS pouches; sachets; dip cups; retail/FS/bulk. Fill temperature unpublished on the co-packing page.",
    productTypesPublished: "High-volume co-pack: condiments, sauces, dressings.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF", "GFSI", "FDA-audited"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-packing", href: "https://www.tulkoff.com/co-packing/" },
    extraLinks: [{ label: "Contact", href: "https://www.tulkoff.com/contact-us/" }],
    overview: [
      "Baltimore, MD and Cincinnati, OH. High-volume co-pack: condiments, sauces, dressings.",
      "Glass/plastic; VFFS pouches; sachets; dip cups; retail/FS/bulk. Fill temperature unpublished on the co-packing page.",
      "SQF, GFSI, FDA-audited. Supports (not always-on): Kosher, Organic, Halal, GF, Non-GMO. MOQ unpublished — not a small-MOQ plant.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Baltimore, MD; Cincinnati, OH",
        formats: "High-volume co-pack: condiments, sauces, dressings. Glass/plastic; VFFS pouches; sachets; dip cups; retail/FS/bulk. Fill temperature unpublished on co-packing page.",
        certs: "SQF; GFSI; FDA-audited. Supports (not always-on): Kosher, Organic, Halal, GF, Non-GMO.",
        moq: "Unpublished. High-volume. Not a small-MOQ plant.",
        usdaVsFda: "FDA-audited. FSIS unpublished.",
        organic: "Organic supported",
        siteLinks: [
          { label: "Co-packing", href: "https://www.tulkoff.com/co-packing/" },
          { label: "Contact", href: "https://www.tulkoff.com/contact-us/" },
        ],
      },
    },
  },
  {
    slug: "sonoma-farm-copacking",
    name: "Sonoma Farm Co Packing",
    sites: [{ city: "Shelby", state: "IN" }],
    locationDisplay: "Shelby, IN",
    processes: [],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: "Bottling. Fill method unpublished.",
    productTypesPublished: "Pasta/pizza, salsa, BBQ, hot sauce, oils, vinegars, mustards, dressings, jams.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Home", href: "https://sonomafarmcopacking.com/" },
    extraLinks: [{ label: "About", href: "https://sonomafarmcopacking.com/about-us/" }],
    overview: [
      "Shelby, IN. Small hands-on. Pasta/pizza, salsa, BBQ, hot sauce, oils, vinegars, mustards, dressings, jams. Bottling.",
      "Fill method unpublished.",
      "FDA-registration / “FDA certified” language. SQF unpublished. MOQ unpublished — do not list as small-MOQ.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Shelby, IN",
        formats: "Small hands-on. Pasta/pizza, salsa, BBQ, hot sauce, oils, vinegars, mustards, dressings, jams. Bottling. Fill method unpublished.",
        certs: "FDA-registration / “FDA certified” language. SQF unpublished.",
        moq: "Unpublished. Do not list as small-MOQ.",
        usdaVsFda: "FDA-registration language. FSIS unpublished.",
        organic: "Unpublished",
        siteLinks: [
          { label: "Home", href: "https://sonomafarmcopacking.com/" },
          { label: "About", href: "https://sonomafarmcopacking.com/about-us/" },
        ],
      },
    },
  },
  {
    slug: "fischer-wieser",
    name: "Fischer & Wieser",
    sites: [{ city: "Fredericksburg", state: "TX", note: "411 S. Lincoln St. per Warehaus" }],
    locationDisplay: "Fredericksburg, TX",
    processes: ["hot-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Hot-fill shelf-stable. No ambient-fill salad dressings, pouch liquids, refrigerated, or powders.",
    productTypesPublished: "BBQ, salsas/chutneys, fruit sauces, marinades, mustards, dessert sauces.",
    moqDisplay: "2,500 units per SKU.",
    publishedSmallMoq: true,
    certs: ["SQF Level 2", "HACCP/HARPC"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-man", href: "https://fwfarmstead.com/co-manufacturing/" },
    extraLinks: [
      { label: "Plant", href: "https://fwfarmstead.com/farmstead-culinary-experiences/specialty-retail/warehaus-store/" },
    ],
    overview: [
      "Fredericksburg, TX (411 S. Lincoln St. per Warehaus). Hot-fill shelf-stable sauces.",
      "Named: BBQ, salsas/chutneys, fruit sauces, marinades, mustards, dessert sauces. Will not run ambient-fill salad dressings, pouch liquids, refrigerated, or powders.",
      "Published floor: 2,500 units per SKU; ~6 weeks from approval. SQF Level 2; HACCP/HARPC. Not on the small-MOQ shortlist.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Fredericksburg, TX (411 S. Lincoln St. per Warehaus)",
        formats: "Hot-fill shelf-stable: BBQ, salsas/chutneys, fruit sauces, marinades, mustards, dessert sauces. No ambient-fill salad dressings, pouch liquids, refrigerated, or powders.",
        certs: "SQF Level 2; HACCP/HARPC. Can run peanuts, sesame, tree nuts, milk, fish, soy, wheat, eggs.",
        moq: "2,500 units per SKU. ~6 weeks from approval.",
        usdaVsFda: "Unpublished",
        organic: "Unpublished",
        siteLinks: [
          { label: "Co-man", href: "https://fwfarmstead.com/co-manufacturing/" },
          { label: "Plant", href: "https://fwfarmstead.com/farmstead-culinary-experiences/specialty-retail/warehaus-store/" },
        ],
      },
    },
  },
  {
    slug: "the-spice-guy",
    name: "The Spice Guy — Sauce Pack",
    sites: [{ city: "Denver", state: "CO" }],
    locationDisplay: "Denver, CO",
    processes: ["hot-fill", "acidified"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "100-gal kettles; hot-fill all products.",
    productTypesPublished: "Acidified foods packer. Hot sauce, BBQ, wing.",
    moqDisplay: "50 gallons per flavor (~1,200 × 5 oz woozy).",
    publishedSmallMoq: true,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Home", href: "https://saucecopackers.com/" },
    extraLinks: [{ label: "FAQ", href: "https://saucecopackers.com/faq" }],
    overview: [
      "Denver, CO. Acidified foods packer. Hot sauce, BBQ, wing. 100-gal kettles; hot-fill all products.",
      "Needs recipe plus scheduled process (or their help) before a quote. Kettle size is not the MOQ.",
      "Published floor: 50 gallons per flavor. “FDA certified Acidified Foods Packaging.” SQF unpublished. Not on the six-plant small-MOQ shortlist.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Denver, CO",
        formats: "Acidified foods packer. Hot sauce, BBQ, wing. 100-gal kettles; hot-fill all products. Needs recipe + scheduled process (or their help) before a quote.",
        certs: "“FDA certified Acidified Foods Packaging.” SQF unpublished.",
        moq: "50 gallons per flavor (~1,200 × 5 oz woozy). Kettle size ≠ MOQ.",
        usdaVsFda: "FDA-certified language. FSIS unpublished.",
        organic: "Unpublished",
        siteLinks: [
          { label: "Home", href: "https://saucecopackers.com/" },
          { label: "FAQ", href: "https://saucecopackers.com/faq" },
        ],
      },
    },
  },
  {
    slug: "el-pinto",
    name: "El Pinto Foods",
    sites: [{ city: "Albuquerque", state: "NM" }],
    locationDisplay: "Albuquerque, NM",
    processes: ["hot-fill", "cold-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Glass, plastic/PET, cups, bulk.",
    productTypesPublished: "Private label / co-pack: salsas, sauces, marinades, dressings.",
    moqDisplay: "Homepage 10,000 units/year. Certs page: minimums vary by pack.",
    publishedSmallMoq: true,
    certs: ["SQF"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Co-pack", href: "https://elpintocopacking.com/" },
    extraLinks: [
      { label: "Services", href: "https://elpintocopacking.com/pages/services" },
      { label: "Certs", href: "https://elpintocopacking.com/pages/certifications" },
    ],
    overview: [
      "Albuquerque, NM. Private label / co-pack: salsas, sauces, marinades, dressings.",
      "Hot-fill (kettle + heat exchanger; filled hot, then cooled). Form also lists cold fill and hold. Glass, plastic/PET, cups, bulk.",
      "Homepage floor: 10,000 units/year. SQF (2025 score 97.5%). Can meet vegan, Non-GMO Project, Kosher, GF, organic; certifiers unpublished.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Albuquerque, NM",
        formats: "Private label / co-pack: salsas, sauces, marinades, dressings. Hot-fill (kettle + heat exchanger; filled hot, then cooled). Form also lists cold fill and hold. Glass, plastic/PET, cups, bulk.",
        certs: "SQF (2025 score 97.5%). Can meet vegan, Non-GMO Project, Kosher, GF, organic; certifiers unpublished.",
        moq: "Homepage 10,000 units/year. Certs page: minimums vary by pack.",
        usdaVsFda: "FDA-filing help. FSIS unpublished.",
        organic: "Capability listed; certifier unpublished",
        siteLinks: [
          { label: "Co-pack", href: "https://elpintocopacking.com/" },
          { label: "Services", href: "https://elpintocopacking.com/pages/services" },
          { label: "Certs", href: "https://elpintocopacking.com/pages/certifications" },
        ],
      },
    },
  },
  {
    slug: "paradigm-foodworks",
    name: "Paradigm Foodworks",
    sites: [{ city: "Lake Oswego", state: "OR" }],
    locationDisplay: "Lake Oswego, OR",
    processes: [],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: null,
    productTypesPublished: "Copack / private label sauces and condiments, conventional and organic. Shelf-stable. Fill method unpublished.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: ["SQF", "Organic Certified"],
    lastVerified: LAST_VERIFIED,
    website: { label: "Copack", href: "https://www.paradigmfoodworks.com/pages/copacking-private-label" },
    extraLinks: [{ label: "About", href: "https://www.paradigmfoodworks.com/pages/about-us" }],
    overview: [
      "Lake Oswego, OR. Copack / private label sauces and condiments, conventional and organic. Shelf-stable.",
      "Fill method unpublished. Formats unpublished.",
      "SQF and Organic Certified. Certifier unpublished. MOQ unpublished.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Lake Oswego, OR",
        formats: "Copack / private label sauces and condiments, conventional and organic. Shelf-stable. Fill method unpublished. Formats unpublished.",
        certs: "SQF and Organic Certified",
        moq: "Unpublished.",
        usdaVsFda: "FDA-approved language. FSIS unpublished.",
        organic: "Organic certified (certifier unpublished)",
        siteLinks: [
          { label: "Copack", href: "https://www.paradigmfoodworks.com/pages/copacking-private-label" },
          { label: "About", href: "https://www.paradigmfoodworks.com/pages/about-us" },
        ],
      },
    },
  },
  {
    slug: "best-brand-bottlers",
    name: "Best Brand Bottlers",
    sites: [{ city: "Sarasota", state: "FL" }],
    locationDisplay: "Sarasota, FL",
    processes: ["acidified"],
    finderProcesses: [],
    finderProducts: ["sauce"],
    packaging: null,
    productTypesPublished: "Private label sauces, marinades, dressings, condiments. Acidified and thermal manufacturing and bottling.",
    moqDisplay: null,
    publishedSmallMoq: false,
    certs: [],
    lastVerified: LAST_VERIFIED,
    website: { label: "Home", href: "https://www.bestbrandbottlers.com" },
    overview: [
      "Sarasota, FL. Private label sauces, marinades, dressings, condiments.",
      "Acidified and thermal manufacturing and bottling. Formats unpublished.",
      "Third-party audited; GMP; SQF in process (not certified on the page fetched). MOQ unpublished.",
    ],
    notes: ["SQF in process — not listed as a current plant cert."],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "Sarasota, FL",
        formats: "Private label sauces, marinades, dressings, condiments. Acidified and thermal manufacturing and bottling. Formats unpublished.",
        certs: "Third-party audited; GMP; SQF in process (not certified on page fetched).",
        moq: "Unpublished.",
        usdaVsFda: "Unpublished",
        organic: "Unpublished",
        siteLinks: [{ label: "Home", href: "https://www.bestbrandbottlers.com" }],
      },
    },
  },
  {
    slug: "onofrios-ultimate-foods",
    name: "Onofrio’s Ultimate Foods",
    sites: [{ city: "New Haven", state: "CT" }],
    locationDisplay: "New Haven, CT",
    processes: ["hot-fill"],
    finderProcesses: ["hot-fill"],
    finderProducts: ["sauce"],
    packaging: "Glass 8–128 oz; hot-fill plastic 8–128 oz; sealed pouches 8–128 oz.",
    productTypesPublished: "No own brand. Sauce and marinade bottling.",
    moqDisplay: "100 case runs.",
    publishedSmallMoq: true,
    certs: ["FDA-approved", "HACCP", "GMPs", "STAR-K kosher parve"],
    lastVerified: LAST_VERIFIED,
    website: { label: "About", href: "https://ultimatefoods.net/about/" },
    extraLinks: [
      { label: "Capabilities", href: "https://ultimatefoods.net/capabilities/" },
      { label: "Certs", href: "https://ultimatefoods.net/certifications/" },
    ],
    overview: [
      "New Haven, CT. No own brand. Sauce and marinade bottling.",
      "Glass 8–128 oz; hot-fill plastic 8–128 oz; sealed pouches 8–128 oz. Kettles 50–1,000 gal (equipment is not the MOQ).",
      "Published floor: 100 case runs. FDA-approved; HACCP; GMPs; STAR-K kosher parve. Certified organic production (certifier unpublished). SQF unpublished.",
    ],
    appearedOn: ["sauce"],
    guideRows: {
      sauce: {
        location: "New Haven, CT",
        formats: "No own brand. Sauce and marinade bottling. Glass 8–128 oz; hot-fill plastic 8–128 oz; sealed pouches 8–128 oz. Kettles 50–1,000 gal (equipment ≠ MOQ).",
        certs: "FDA-approved; HACCP; GMPs; STAR-K kosher parve. Certified organic production (certifier unpublished). GF capability. SQF unpublished.",
        moq: "100 case runs.",
        usdaVsFda: "FDA-approved. FSIS unpublished.",
        organic: "Certified organic production; certifier unpublished",
        siteLinks: [
          { label: "About", href: "https://ultimatefoods.net/about/" },
          { label: "Capabilities", href: "https://ultimatefoods.net/capabilities/" },
          { label: "Certs", href: "https://ultimatefoods.net/certifications/" },
        ],
      },
    },
  },
];

export const DIRECTORY_PLANTS: Plant[] = [...CURATED_PLANTS, ...IMPORTED_PLANTS];
